### ISSUE TITLE
Flood insurance for your inbox - stop watching GitHub but Subscribe to issues of interest

### ISSUE THREAD

**Issue by egawiser** [LSSTScienceCollaborations/ObservingStrategy#133]
So it took some of us a while, but if your inbox overflowed this week and you didn't like it, you can stop Watching the ObservingStrategy repository (35 of you still are) and it will still email you when you "participate" or are "mentioned" in an issue.  You can also scroll through issues periodically and Subscribe (button on the lower right, separate from "Watch") to any you weren't yet mentioned in but want to hear updates about.

**Comment by drphilmarshall** [comment]
Thanks @egawiser! To "unwatch" the repository in this way, just click on the "unwatch" button!

![image](https://cloud.githubusercontent.com/assets/710903/9425196/4100800c-48bc-11e5-8507-9d40d82209b0.png)

To keep communication working well, though, we all need to agree to start @mentioning each other by username (like I just did with @egawiser), so that the mentioned people DO get a notification. Thanks!

**Comment by janewman-pitt-edu** [comment]
Thanks :)

Jeff

**Comment by drphilmarshall** [comment]
SO MANY ISSUE NOTIFICATIONS!
Don't forget you can [hit the "Unwatch" button](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/133#issuecomment-133734982) to just get notifications from issues where you are @mentioned. Or you can carry on happily skimming and deleting :-)
