### ISSUE TITLE
Split Variables and Transients Chapter into smaller sections

### ISSUE THREAD

**Issue by ebellm** [LSSTScienceCollaborations/ObservingStrategy#152]
The science and metrics in the current Variables and Transients chapter are too broad to cover adequately.  I suggest we break it up into science-driven chapters:

* Galactic variable sources (stellar and binary sources).  
* AGN
* Extragalactic (or explosive?) Transients (supernovae, GRBs)

**Comment by AshishMahabal** [comment]
I agree.
We may want to combine AGN with the extragalactic transients though since there may not be enough in terms of AGN variability to make a separate chapter.

**Comment by AshishMahabal** [comment]
Participate in this doodle poll to decide on a time Thursday Oct 1 to have further discussion on this issue.
http://doodle.com/poll/uc64cis3gancz46b

**Comment by jhrlsst** [comment]
I think observing strategy of SN can belong to SN cosmology section together since there is  not much difference of observing strategy
between Type I and II (maybe except GRB). SN Cosmology section can be renamed "SN cosmology and physics" (or SN physics and Cosmology) which will take care of inclusion of Type II. This way we can focus optimizing observing strategy to detect supernovae. We can merge the authors as well, as needed. We will select SN candidates first and then classify them into Type I or II.
We can discuss more on this during the telecon we are doing doodle poll.

**Comment by jhrlsst** [comment]
What is telecon number to join at 2pm? I cannot find the email.

**Comment by AshishMahabal** [comment]
A summary of the telecon yesterday.

Hi,

Thank you to close to 10 participants who were present at the telecon.
People present included Ashish, Darko, Eric, Fed, Jeonghee, Kem, Lucianne, Rahul, Steve (please let me know if I have missed anyone).
Alexander, Marc, Rob, Shashi sent apologies
(Alexander/Marc, we should indeed try bluejeans next time so that people outside the US can call in)

We decided that the AGN chapter can be separate as they want, and we will refer to the AGN variability in different sections where it makes sense because of whatever similarity there is.

We decided that SN can/should be in both cosmology and in the TVS chapter. We are doing the White Paper exercise not on the basis of scientific lines (alone) but primarily on the lines of observability and attendant metrics.

Eric reiterated the division he had in mind which we can fine tune further. Details below.

The rolling cadence part can stay, and be elaborated upon and then we can take another look at it if needed.

Finally please contact as many TVS folks as you can - personally - to encourage them to provide text and arguments for their science. Especially if they have generated metrics which need inclusion and elaboration.

Our main site for discussion should be the github repo. I will post this there. TVS members who have not been active there will see his email, but should directly respond there: https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/152

The Tucson meeting is in the middle of Nov. Lets try to do as much work we can well before that.

-ashish

Details from Eric on the division (we can fine tune as needed. Later there will an effort to fit it in with the non-TVS parts as well):
Galactic variable sources (stellar and binary sources).
    This will split into periodic variability, aperiodic variability
(YSOs, for instance; connection to AGN), secular trends (ie, period
derivatives). and potentially outbursts (see below).  The periodic
section is largely complete.  The unifying thread for this chapter is
that these are objects where we care about the variability (not static
science) but we expect the objects to be detected throughout the
lifetime of the survey.

AGN
   The AGN folks have indicated they are interested in their own
chapter.  I think the structure function/damped random walk type
fitting is used largely with AGN, so their metrics are also somewhat
unique.

Extragalactic (or explosive?) Transients (supernovae, GRBs)
  For SNe, the emphasis here is on SNe as astrophysical objects, not
SNe as probes.  So cadence-related metrics here would include things
like discovery rates of rare subtypes or young SNe, shock breakout
detection, pre-explosion outbursts, spectroscopic accessibility, etc.
rather than Ia lightcurve sampling.
  For GRBs Eric is working on some metrics on orphan afterglow discovery rates.


An open question in my mind is where to put outbursting Galactic
objects like CVs--with explosive transients, based on metric
similarity?
--------------------------------

**Comment by StephenRidgway** [comment]
Eric’s suggestion:

This will split into periodic variability, aperiodic variability
(YSOs, for instance; connection to AGN), secular trends (ie, period
derivatives). and potentially outbursts (see below).

Science areas treated elsewhere, which have same or related metrics, could be mentioned (on a case by case basis) by reference to other chapters.

And then rolling cadence appended at the end - at least provisionally.

I think this is an improvement and the criteria are easy to understand.  If the sections were to become too large they could be divded into 2 or more chapters.


Steve

**Comment by drphilmarshall** [comment]
@StephenRidgway I think you should go ahead and split the V&T chapter up into new science-oriented chapters. I will take care of making a new AGN chapter. Thanks!

**Comment by StephenRidgway** [comment]
I understood an agreement to “split off” several topics including SN, AGN, which I think is mostly done, leaving mostly galactic variables in T&V chapter.  Did you see further splitting at this time?

**Comment by drphilmarshall** [comment]
@ebellm I think this is a question for you - but it might also be for the
other V&T chapter editors.

**Comment by AshishMahabal** [comment]
@ebellm Indeed, can you do that please? I will try to drum up interest among other should-be-stakeholders to pitch in

**Comment by ebellm** [comment]
Okay, I am working on the split described above (Galactic variables, Explosive transients).  @StephenRidgway, I think the rolling cadence discussion fits most naturally into Chapter 2 (Alternative Observing Strategies)--objections to moving it there?

**Comment by StephenRidgway** [comment]
No objection from me.

**Comment by jhrlsst** [comment]
Splitting into Galactic variables and Explosive transients sounds good to me.
Since we are spending a lot of time on observing strategy for SN cosmology and think about classification of SN types, the main strategy will be in the SN cosmology section. In the variable section, we will cite SN cosmology section. However, GRB part is very different. Thus I predict in this variable section, more items for GRB than those for SN Type II.
