### ISSUE TITLE
Photometric redshifts and/or clusters section

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#198]
Should we add a section on clusters in the white paper and if so, what metrics (if any) do we need for this section? Who will write it? Also, should we add a photometric redshift section and metric? I personally think this is missing from the white paper as it affects basically all cosmology cases and I think can be quite strongly affected by observing strategy. What do others think?

**Comment by drphilmarshall** [comment]
I agree that photo-zs are very important to include. The WL and LSS groups
(and basically everyone else in DESC) should be highly motivated to check
that the proposed strategy will deliver the required photo-z accuracy,
including after 1 year, 3 years etc, and also in the WFIRST, Euclid and
other redshift survey areas that might be being considered for photo-z
calibration. It would be bad if these spectroscopic calibration fields were
not observed in the right way early on, no? Great if @sschmidt23 and
@janewman can provide some guidance here.

I'd suggest that we prioritize photo-zs over clusters for now: once we have
metrics that quantify PZ and WL performance, a CL figure of merit can
probably be constructed fairly easily (although they may already care now
about overlap with other surveys in eg the X-rays - @idellant?)  Let's go
ahead and start a PZ section and write some starter text in it, so that
others in DESC can contribute easily when called upon.

**Comment by connolly** [comment]
@sschmidt23 and @janewman I'm working on an accuracy vs m5 depth photoz
performance calculation. Hope to have something interesting later today.
Would be good to decide if we want to modify the current metrics for photoz
(scatter, bias, fraction of outliers) and their thresholds.

cheers
Andy

**Comment by janewman-pitt-edu** [comment]
There are two separate parts of the photoz issue.

One impact is variation in depth and zero point imprinting on LSS.  I'm working with Sam and Eric (as well as a student at Pitt) to try to assess relative impact of the different bands on this (by getting random forest importance weights for the different bands), allowing Eric's single-band power spectra to be propagated into something related to net effects on photo-z's.

The other impact is if variations in depth cause us to miss our photo-z requirements.  The complicated thing is that we care about depth in all bands, but photo-z's will degrade slowly with a given band.  I suppose ideally we'd come up with a function that maps all of the bands' depths into the photo-z errors/outlier rates at our limiting magnitude, and can compare to requirements, but it's very complicated and I don't see a tractable way to do that with the limited available resources (mostly time) that we have.  However, if we minimize variations in depth on other bases (e.g. LSS), we'll also be minimizing them for photo-z's and this gets resolved automatically.

**Comment by sschmidt23** [comment]
I think Jeff summarized things well, though Phil's statement that once PZ requirements are characterized it will be easy to propagate to Clusters makes me want to add the caveat that Joe Zuntz brought up at the Argonne meeting, namely that the general PZ statistics will not be the same as those for the specific science cases because each science case will have specific selections on top of the general PZ catalog.  A good example of this that Joe brought up was the WL samples in the DES Bonnett et al paper (link)[http://arxiv.org/abs/1507.05909].  This is a bit more nuanced than we probably want/need for the observing white paper, but it is a real issue.

And @connolly I will be very interested to see what you have for statistics as a function of m5 depth, please send those along when you have some plots/tables/writeup.

**Comment by drphilmarshall** [comment]
My audit ( #304 ) showed no content on photo-zs yet, so I suggest we punt this to white paper version 2! Re-milestoning.

**Comment by janewman-pitt-edu** [comment]
Andy's working on this with Melissa Graham -- we've been emailing about it today, in fact.

**Comment by connolly** [comment]
We have some early results on scaling of photoz errors with survey
progress  but not in the form of a metric. What are the next milestone
dates?

On Thu, Apr 28, 2016 at 7:48 PM, janewman-pitt-edu <notifications@github.com

**Comment by janewman-pitt-edu** [comment]
As I understand it, it�s OK to present a plan for a metric at this point, rather than the metric itself.

Best,

Jeff

**Comment by drphilmarshall** [comment]
Yeah, that's right - and if you have quantitative results that depend on
any OpSim-output quantity, that qualifies as a result and your own section
(rather than an entry in "Future Work"). I don't see any content in
`Cosmology/photoz.tex`, so I'm going to assume this will be a late entry to
version 1 at best, and more likely a contribution to version 2. Deadline
for the final draft was Thursday, and internal review is happening this
week: all the Cosmology issues are now closed, which means the rest of the
chapter is ready to be sent out for review. We'll press on with this, but
if you can get a photo-z section finsihed and pushed by mid-May, we can get
it reviewed and polished by May 27th (which is when we submit version 1 to
the LSST pub board). Thanks very much for getting moving on this! :-)

**Comment by MichelleLochner** [comment]
We now have the beginnings of a great photo-z section! Thanks for the hard work everyone!
