### ISSUE TITLE
Workshop registered attendees list

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#22]
@StephenRidgway wrote: 

> I thought that I understood from discussion Tuesday that there is a list of persons who have registered for the cadence workshop, but at the registration site I only find an inclusive list for all persons attending during the week.  Can anybody point me to the cadence workshop attendee list, or confirm that there is not one?

If there is not one, we need to make one. Assigning this to @ivezic so he can re-assign to the right person!

**Comment by ivezic** [comment]
Daniel and Emily acted promptly and produced this list of people who
registered for Aug 20, 21, or 22: 
https://project.lsst.org/meetings/lsst2015/cadence-registrations

It's not ideal because there are some people who stay until 20th, and not
for the workshop. However, it's easy to count those who stay by searching
for string "21". There are 85 people (out of 105) who apparently will attend
our workshop.
