### ISSUE TITLE
Missing supernova figures

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#234]
Jeonghee there is a missing figure, SN_309_lcavg.pdf, in the supernova section preventing compilation of the white paper. Please add that figure and commit as soon as possible.

**Comment by jhrlsst** [comment]
I commented it out for now since I don't have time now (feel free to comment out this type of things if it happens again).
Rahul and I am generating a few more figures and I will add them together next time when I have a chance. As you see the pdf file on the git page, the latex seems to be successfully compiled.
