### ISSUE TITLE
Transients chapter 6.5: GW TOOs

### ISSUE THREAD

**Issue by ebellm** [LSSTScienceCollaborations/ObservingStrategy#240]
@soares-santos @ehneilsen We need to develop some science justification text for the EM/GW TOO section.  I think this includes:
* describe the EM/GW science and why LSST TOOs are needed
* give plausible ranges for counterpart color, luminosity, decay timescales, number of triggers
* propose a sequence of TOO observations

To zeroth order I don't know that we actually need a metric--the first goal in my mind is to confirm that TOO observations at some modest level don't disrupt the LSST programs unduly.

Presumably eventually it would be valuable to assess how well the TOO observations actually get scheduled in terms of detecting a counterpart; we might be able to use some of the existing transient metrics for this, if the TOO observations can be selected from the OpSIM output in some obvious way.

**Comment by ebellm** [comment]
cf #113

**Comment by fedhere** [comment]
I will be responsive on this starting next week. Sorry : till then teaching
takes 100% of me...

On Thursday, December 17, 2015, Eric Bellm <notifications@github.com> wrote:

> cf #113
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/113>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/240#issuecomment-165612457>
> .
>


-- 

_____________________________________________

dr. federica bianco
James Arthur Fellow
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/
___________________________________________

  //\\
 //||\\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by drphilmarshall** [comment]
Thanks Eric! As part of the justification text on TOOs, will there be a
section on what can be done just with the WFD observations planned? There's
usually *something* that can be done with the LSST survey data as-is, and
it would be good to have this sketched out as the baseline before
requesting TOO observations on top of that. And of course if there *is*
something that can be done with the survey data as-is, that will need
quantifying with some metrics.
