### ISSUE TITLE
Make separate tex files for each section

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#26]
Dear all, 

Can you please make a tex file for your section, by copying the [template](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/section-template.tex) called [section-template.tex](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/section-template.tex)?  Let's keep the file names simple - just choose a single lower-case string capturing the name of your science case/project. 

Thanks!

Phil

**Comment by StephenRidgway** [comment]
I followed Phil's request to use the section model and prepared 5 skeleton sections for the chapter 5 on variables and transients.  Several of us are currently leaning toward including multiple science topics in some sections, in order to group them approximately by requirements.  Also, the section on rolling cadence is not a science section, so I adjusted the model even more there. I see both advantages and problems with using one section model throughout, but am here proposing some deviations from uniformity.  Maybe somebody sees another way.

**Comment by drphilmarshall** [comment]
I think grouping by expected requirements makes sense (that's kind of how
we designed the chapters). Maybe try starting out the way you have it, and
if you find that each science sub-section grows too big, you could try
splitting them into their own separate sections (still grouped by
chapter).  My "one science project per section" scheme was designed to be
maximally modular, to allow re-ordering and re-grouping later as required -
and also to appeal to the section leads, who I figured would work best if
they only had to think about their single favorite science project.

**Comment by drphilmarshall** [comment]
Closing this, as the sections are now issued individually.
