### ISSUE TITLE
Illustrative light curves

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#268]
A thought occurred at the AAS meeting: we must make sure we that the white paper includes a representative set of simulated/realized light curves, for various transient and variable objects. Jackie Moreno is making these for AGN, and I think @rbiswas4  is too for SNe. If we make some nice figures, they could also be extracted and used on the LSST website to help give people an idea of what to expect. Action: Phil to look through paper for these and assign people with inserting suitable figures.

**Comment by fedhere** [comment]
i think we have all the gear to do this for the transients in chapter 6 as well

**Comment by rbiswas4** [comment]
There are actually a few in the cosmology (SN section). This will be expanded.

**Comment by drphilmarshall** [comment]
Cool, thanks both! I say, go ahead and make your nifty figures, and ping me
if you think of it - and don't worry if you don't, Ill find them eventually
:-)

**Comment by jhrlsst** [comment]
Rahul and I have been preparing for a number of SN light curves towards different parts of the sky.
Do you know if the new sets (updated) of opsim outputs are available since we want to use the updated version? Please let us know when they are available. We can do this within 1 or two weeks.

Jeonghee

**Comment by lundmb** [comment]
I have these for transiting planets in a few published papers already, and
I do have the tools to create a light curve for anything else with a simple
functional form.

- Mike Lund

**Comment by jhrlsst** [comment]
I added a number of light curves in the SN cosmology chapter. Feel free to look at them.
Jeonghee

**Comment by drphilmarshall** [comment]
Thanks all - I'm going to assume this is all good now.

**Comment by fedhere** [comment]
we are collecting lightcurves for a variety of eruptive and explosive
transients, following the LSST TVS roadmap meeting two weeks ago.



On Sat, Jan 9, 2016 at 3:16 PM, Phil Marshall <notifications@github.com>
wrote:

> A thought occurred at the AAS meeting: we must make sure we that the white
> paper includes a representative set of simulated/realized light curves, for
> various transient and variable objects. Jackie Moreno is making these for
> AGN, and I think @rbiswas4 <https://github.com/rbiswas4> is too for SNe.
> If we make some nice figures, they could also be extracted and used on the
> LSST website to help give people an idea of what to expect. Action: Phil to
> look through paper for these and assign people with inserting suitable
> figures.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/268>
> .
>



-- 

_____________________________________________

dr. federica bianco
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/
___________________________________________

  //\\
 //||\\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.
