### ISSUE TITLE
Allowed ranges for observing strategy modifications

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#27]
In the white paper sections, various tweaks to the observing strategy will be suggested, so some brief discussion of what is and is not within our scope might be in order, while we are still getting going. Examples of modifications I can imagine being proposed include: varying the exposure time, adding more sky area in the North, exposing with no filter present, and so on. @ivezic, where's the best place to look for our constraints, when speculating about strategies that might improve our metrics? Is it your overview paper? Are there ranges of acceptable parameters that the OpSim team is "allowed" to explore within? I think it would be very useful to see this already laid out in the white paper introduction when we get to Bremerton.

**Comment by ivezic** [comment]
There were useful talks at the last workshop
https://project.lsst.org/meetings/ocw/node/6

In particular, this talk discussed overall constraints on cadence due to finite etendue etc 
https://project.lsst.org/meetings/ocw/sites/lsst.org.meetings.ocw/files/IvezicCadenceWorkshop2014v2.pdf

Yes, it would be good to turn all that into prose in introduction.

**Comment by drphilmarshall** [comment]
Thanks Zeljko!

**Comment by drphilmarshall** [comment]
Hey @ivezic! Is this issue resolved to your satisfaction? If so please close it out - thanks!
