### ISSUE TITLE
WFIRST + LSST weak lensing: science project definition, figure of merit

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#273]
Over to you, @jasondrhodes ! I made you `WFIRST_weaklensing.tex` for your outline - best to keep things simple, I'd say.

**Comment by jasondrhodes** [comment]
I don't see that file @drphilmarshall.   Also, can we call it something list WFIRST_HLS where HLS=high latitude survey.  This is about more than WL.

**Comment by jasondrhodes** [comment]
also, I think I should see a file that is the WFIRST overview chapter (or section).  I am ready to edit that as well.  Sorry if I am missing something obvious as I am not very experienced on github.

**Comment by drphilmarshall** [comment]
Apologies, this was my fault. All files are now added and pushed.

**Comment by drphilmarshall** [comment]
Hi @jasondrhodes  I moved your WFIRST intro into the chapter file, `wfirst.tex` in the main `whitepaper` folder. Do a `git pull` and see what you think! Are you ready for your section to be reviewed, or is there a simple approximate quantitative analysis to add, about what you could do even if LSST ran with the baseline cadence? This would help show the path forward to a full metric analysis in later versions of the paper. Thanks!

**Comment by jasondrhodes** [comment]
@drphilmarshall @mtpenny @jasondrhodes I had a question about this claim: "These will allow microlensing parallax measurements to
determine the distances and masses of a representative sub-sample of the rogue planets found by
the WFIRST  microlensing survey. These measurements will be crucial for the interpretation  of
WFIRST’s rogue planet discoveries, and they cannot be obtained by another method.:  Why is this the only method allowable?  Can't Subaru do this as well?  Is an 8 meter telescope needed?

**Comment by jasondrhodes** [comment]
@drphilmarshall Sorry for the belated reply.  I made some changes to the latex files for weaklensing, microlensing,and the wifirst intro.  I will try to check those into GitHub (but I have had trouble doing that before).  If it doesn't work, I will send those latex files.  I thought you had some supernova text from @rubind  but I did not see it in the supernova latex file I downloaeded.  Can you confirm it has been added?  I think the weaklensing and microlensing sections are definitely ready to be edited.  I don't think it is beneficial to be more quantitative about the weaklensing yet because the wfirst survey and filters are still in flux.

**Comment by drphilmarshall** [comment]
OK, thanks Jason! I will merge your changes in first, and then David's
(which are waiting in pull request #397 ), and then look to get them
reviewed.

**Comment by drphilmarshall** [comment]
Closing this: I am effectively reviewing (and editing!) your WFIRST WL text in PR #413
