### ISSUE TITLE
LaTeX infrastructure

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#3]
* [x] Chapter folders, with latex files
* [x] Global latex files: main, macros, references.
* [x] Makefiles
* [x] README

**Comment by drphilmarshall** [comment]
Hi all - I just checked in a skeleton latex structure for the Observing Strategy white paper. Can you please  git pull and try making it, and submit any issues that arise? Thanks!

**Comment by ivezic** [comment]
After running make, I got this:
! Undefined control sequence.
<recently read> \FamilyKeyStateProcessed                                       
l.1268 }

If you let it continue, it will complete, but the resulting pdf definitely looks like something 
went wrong. Googling it (though not very hard) didn't make me smarter...

**Comment by drphilmarshall** [comment]
Hmm. I can't reproduce this error, even in a fresh clone. Can you send me the entire `LSST_Observing_Strategy_White_Paper.log` file, please, so I can diagnose better? Thanks!

**Comment by ivezic** [comment]
The problem seems to be a wrong version of the KOMA-Script package (see below). 
I will investigate later how to fix it. If this is something common, please let me know. 


Document Class: scrbook 2013/12/19 v3.12 KOMA-Script document class (book)
(./scrkbase.sty
(/usr/local/texlive/2012/texmf-dist/tex/latex/koma-script/scrbase.sty

LaTeX Warning: \KOMAScriptVersion  is `2013/12/19 v3.12 KOMA-Script',
               but `2012/05/15 v3.11 KOMA-Script' was expected!
               You should not use classes, packages or files from
               different KOMA-Script versions.

(/usr/local/texlive/2012/texmf-dist/tex/latex/graphics/keyval.sty)
(./scrlfile.sty
Package scrlfile, 2013/12/19 v3.12 KOMA-Script package (loading files)
                  Copyright (C) Markus Kohm

))) (/usr/local/texlive/2012/texmf-dist/tex/latex/koma-script/tocbasic.sty)

LaTeX Warning: You have requested, on input line 114, version
               `2013/12/19 v3.12 KOMA-Script ' of package tocbasic,
               but only version
               `2012/04/04 v3.10b KOMA-Script package (handling toc-files)'
               is available.

! Undefined control sequence.
<recently read> \FamilyKeyStateProcessed

**Comment by drphilmarshall** [comment]
Good, thanks - this is because your local version of the koma-script style files is older than the one I checked in - I know one shouldn't distribute files like this along with latex source, but I was trying to enable people to get up and running quickly... So, I checked in `tocbasic` for you. Try `git pull` and re-make, and let me know how it goes...

**Comment by ivezic** [comment]
Did it, no change. I just cloned it from scratch and still don't see tocbasic. Where
should I look for it?

**Comment by drphilmarshall** [comment]
My mistake - it's there now.

**Comment by ivezic** [comment]
I got tocbasic.sty now, but the problem remains:

(./scrbook.cls
Document Class: scrbook 2013/12/19 v3.12 KOMA-Script document class (book)
(./scrkbase.sty
Package: scrkbase 2013/12/19 v3.12 KOMA-Script package (KOMA-Script-dependent b
asics and keyval usage)

(/usr/local/texlive/2012/texmf-dist/tex/latex/koma-script/scrbase.sty

LaTeX Warning: \KOMAScriptVersion  is `2013/12/19 v3.12 KOMA-Script',
               but `2012/05/15 v3.11 KOMA-Script' was expected!
               You should not use classes, packages or files from
               different KOMA-Script versions.

Package: scrbase 2013/12/19 v3.12 KOMA-Script package (KOMA-Script-independent 
basics and keyval usage)
(/usr/local/texlive/2012/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 1999/03/16 v1.13 key=value parser (DPC)
\KV@toks@=\toks14
)
(./scrlfile.sty
Package: scrlfile 2013/12/19 v3.12 KOMA-Script package (loading files)

Package scrlfile, 2013/12/19 v3.12 KOMA-Script package (loading files)
                  Copyright (C) Markus Kohm

))) (./tocbasic.sty
Package: tocbasic 2013/12/19 v3.12 KOMA-Script package (handling toc-files)
)
Package tocbasic Info: omitting babel extension for `toc'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `toc' on input line 117.
Package tocbasic Info: omitting babel extension for `lof'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `lof' on input line 118.
Package tocbasic Info: omitting babel extension for `lot'
(tocbasic)             because of feature `nobabel' available
(tocbasic)             for `lot' on input line 119.
Package tocbasic Info: defining new hook before heading of `' on input line 111
8.

! Undefined control sequence.
<recently read> \FamilyKeyStateProcessed 
                                         
l.1268 }

**Comment by drphilmarshall** [comment]
Hmm. OK, try moving the koma-script files out of the repo. If this now
comes as standard with latex, everyone should be able to use their local
installation. The following commands all worked for me:

    mv scrbook.cls scrkbase.sty scrlfile.sty tocbasic.sty tocstyle.sty
notes/
    make clean
    make

**Comment by ivezic** [comment]
It worked for me too, thanks!

**Comment by drphilmarshall** [comment]
OK, can you commit and push those changes, please? If anyone else has trouble compiling due to lack of koma-script files, we'll start a new issue. Thanks @ivezic!
