### ISSUE TITLE
Variable & Transient Sources chapter

### ISSUE THREAD

**Issue by StephenRidgway** [LSSTScienceCollaborations/ObservingStrategy#30]
I've uploaded files constituting a first draft of Ch 5, which has been fleshed-out another level deeper from the original outline.  This is one of the more complex chapters. You might want to scan to see some deviations I made from Phil's outline, pretty minor I think.  This is my unreviewed hacking so blame me for any nonsense.  I can email a pdf if you are not yet corresponding with github.

**Comment by drphilmarshall** [comment]
Looks good, thanks @StephenRidgway ! One thing: can you please attach section lead names to each section so that we can keep track of who is doing what? We'll need to issue those people with working on their individual sections, so we'll need the names for that alone. You could write the issues yourself, as chapter lead! :-)

**Comment by StephenRidgway** [comment]
Hi Phil,

Waiting to see who is able to devote some time to this.  I think we have to rely on contributors to insert their own bylines : )

Steve

**Comment by drphilmarshall** [comment]
Sounds good to me! Hopefully the contributors will be making the PDF as
they edit, and they'll notice that their names are not listed and fill them
in :-)
