### ISSUE TITLE
Condense or split up Milky Way Disk section?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#375]
@willclarkson @akvivas 

The Disk section is quite long at the moment, and arguments can be made for either splitting it up, or just condensing the text around the common metrics. It's up to you :-) Please discuss, decide and execute! Thanks :-)

**Comment by willclarkson** [comment]
Hi @drphilmarshall -- @akvivas and myself just discussed this issue. I believe our consensus is to keep the section as-is for the moment (rather than splitting the cases out), with a view to revisit in mid-May once there has been time for our collaborators to work a bit more on evaluating the Figures of Merit in that section. The current structure is one I can imagine going into a refereed publication (e.g. "Examples of low-latitude populations LSST will study," but obviously worded a bit better...

One idea that did occur, is just to rename that section from "Mapping the Disk" --> "Populations in the Milky Way Disk" -- that way it's clear from the beginning that there will be a few example populations there.

@akvivas and @drphilmarshall - unless I hear otherwise, I will go ahead and rename Section 4.2 in this manner.

**Comment by willclarkson** [comment]
Section 4.2 renamed to "Populations in the Milky Way Disk." I'm closing this issue for now.

**Comment by willclarkson** [comment]
whoops - should have reassigned not closed. Sorry!

**Comment by drphilmarshall** [comment]
This is fine with me. Thanks both!

**Comment by willclarkson** [comment]
Seems to have been addressed; closed.
