### ISSUE TITLE
Workshop design

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#4]
Write markdown file outlining workshop plans, including:

* [ ] Meeting schedule - talks, hack sessions.
* [ ] Pre-workshop tutorials
* [ ] Post-workshop activities and timeline
* [ ] Community building - workshop email list, these issues, etc.
* [ ] Advertising: meeting website, email timeline etc.

**Comment by drphilmarshall** [comment]
Hey @lmwalkowicz, want to have a go at tweeting some meeting wisdom into [the notes](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/workshop/notes/design.md)? Mainly what we need are some *principles* at this stage, I think.

**Comment by drphilmarshall** [comment]
BTW as soon as @djbard and @connolly accept their invitations, you can re-assign this issue to them!

**Comment by djbard** [comment]
Suggestion from @bethwillman:

Day 1 and first morning session of Day 2 - People from the community at large and within the existing collabs, especially those who have objected in the past to any aspect of (what they perceive to be) LSST's plan, give talks that present an issue related to the science cases under scrutiny + related quantifiable cadence needs. They could be given specific guidance prior to the workshop on how to best present the quantifiable technical needs.

The evening of Day 1 could be setting up a hack session for the next day - Some pre-selected community members/pundits pitch their ideas, a team of self-identified super users gather around metric(s) they are interested to tackle, and some information is exchanged. We could engage science collaboration chairs to advertise this opportunity as a way for collaboration members to provide support to the science collaborations. (People often ask how they can help.) A combination of sci collab members and Project members could thus form the hack day teams (along the lines of the current vision).

Day 2 - People who will not be hacking metrics attend discussion/talk sessions about (for example) cross facility work, with a couple of hours reserved for checking in with the hack teams to provide clarifying information as needed.

Day 3 morning - A report from the hack sessions and a report from the cross facility conversations.

**Comment by lmwalkowicz** [comment]
I like these suggestions @bethwillman! For Day 2 we could add an unconference element to the discussions to make them flexible and responsive to who is attending and other issues that arise (rather than presetting the topics, though of course we can have some in mind). If you don't know what I mean by unconference:
1. we make a big grid (on a white board or poster board) with time slots and the meeting spaces we have access to. 
2. At a specified time (after this idea has been explained to them) attendees interested in particular topics post those topics in one of the meeting place/time boxes. Posting attendees are encouraged to combine sessions if they have similar topics/goals. 
3. The board then forms the schedule of discussions for that day.

**Comment by drphilmarshall** [comment]
Zeljko circulated a proposed schedule. @ivezic can this be inserted into the workshop design notes, for people to see when they come looking after the first announcement? We also need to decide how much draft schedule to put on the webpage, as issued to Lucianne at #13

**Comment by drphilmarshall** [comment]
@lmwalkowicz It looks as though this one can be closed at the same time as #13 and #6 !
