### ISSUE TITLE
Feedback on Chapter 2 Introduction (2.1) and Baseline Cadence (2.2)

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#422]
@AshishMahabal Would you be willing and able to read and comment on 2.1 and 2.2 please? We need the baseline cadence section to contain a sufficient description of the main OpSim output that the science analyses are using, and the introduction needs to present it well. I think its good to read both together, and in the light of what you know is coming in, for example, the transients and variables chapters. 

You can [download and view the v0.8 PDF here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or comment/edit the current version in `master` if you prefer. Great if you can either post comments and queries to this issue thread, or make new issues assigned to suitable people if you see things that need fixing. 

Thank you!

**Comment by AshishMahabal** [comment]
Will do

**Comment by drphilmarshall** [comment]
Great, much appreciated.

**Comment by AshishMahabal** [comment]
Making slow but definite progress on this. Things look great so far. Hope to finish later today.

**Comment by bethwillman** [comment]
This Chapter overall is in great shape.  The jargony figure titles (even moreso throughout other chapters the White Paper) make the figures hard to quickly read and understand - e.g. CoaddM5 doesn't mean anything to the audience for this white paper.  If the Figure titles and legends don't make sense, then people won't show figures in their talks and posters.  Can these be changed?

**Comment by rhiannonlynne** [comment]
Yes, the figure titles and legend labels can be changed. These are
generally the default titles from maf, which (hopefully!) make a lot of
sense to the people making the figures and are provided to help track which
figure came from where/what metric, etc.
However, they are pretty easily changed by a user.

Probably the opsim name should remain in figures though, as otherwise it is
way too easy years later to be confused about why you got x result and
where it came from (we've had this problem with neo runs). The caption end
up separated from the figure.

**Comment by bethwillman** [comment]
Good point re: the OpSim name in the title, Lynne.

**Comment by michaelstrauss** [comment]
Hello all,
  Here's a detailed set of comments on Chapter 2, which I have now read through in some detail. 

 First, some initial statements:

  I think we need to have more of an introduction about some basic things.  First, OpSim itself is described in only a sentence or two, with a reference to the overview paper and the science book for details.  OpSim is absolutely core to the entire white paper, and I think we should include several paragraphs here (or perhaps in Chapter 1) describing how it works.  This will make the white paper more self-contained. 

  Similarly, the rules of the universal cadence are never properly stated.  We learn, eventually, that there is something about revisiting a given field on a given night, because of asteroids (must this revisit be in the same filter?  Does it happen even in u?), but we learn nothing else about the rules.  These need to be clearly stated. 

  (By the way, we need to clearly define and make the distinction between these terms:
     -The baseline cadence (old and new) (By the way, haven't we already decided that minion_1016 is the new baseline?)
     -The universal cadence
     -The WFD cadence (same as universal cadence, right?)

  I really think we should give our different OpSim outputs more meaningful names than kraken_1043 and minion_1012.  I would suggest doing a global replacement something like:
   \def\minion_1012{\tt Universal\_Cadence}
There is a table at the beginning of Chapter 2, listing them all, but making the reader constantly switch back to that to remember the distinction between these seems unfair. 

  OK, more details, reading sequentially through: 

  Chapter 2: Perhaps rename to: "The Operations Simulator and its Outputs".  These outputs will be used throughout the rest of the white paper. 

  Section 2.2, again isn't minion_1016 now officially the new baseline cadence? We should say so. 

  Fig 2.1 caption: I didn't understand the parenthetical remark about the bifurcation of the Galactic equator. Also, isn't the airmass limit 1.4, not 1.5?  There's a contradiction with Chapter 1. 

  Figure 2.3: perhaps also include histograms. 

  Bulleted list in Section 2.2, starting page 19:
     1.  Am I correct that there are 5 deep drilling fields, 4 of which have been settled?  We should list them all, and make sure the description in Chapter 1 is consistent.  Also describe the cadence rules for them. 
     2.  The total exposure time is incorrect by an order of magnitude. 
     3.  In the description of the OpSim, we should state how long a filter change takes, otherwise the reader doesn't know why they should care about the number of filter changes. 
     4.  Explain the distinction between effective seeing and geometric FWHM; this will require an equation or two. 
     5.  I got confused about the moon avoidance problem.  Is the point that OpSim is allowed to get too close to the moon? 
     Given these whopping problems with sky brightness, I think this needs to be stated clearly near the beginning, in the description of OpSim. It is unclear in what is written here to what extent the fact that we are not going as deep as we originally said we would is due to mistakes we will fix (over-estimated sky) or to a real change in what LSST will deliver.  This is important.  
  I would also explain more clearly how depths are calculated.  Footnote 4 has some confusing words about the way it is scaled from the depths at zenith in dark skies, but it is not clear to the casual reader how those are calculated, or how that scaling is done.  This is important, and needs to be expanded upon in the main text. 
     6.  There is an on-going confusion on the distinction between the 85% of the time spent on the main survey, and the statement in the opening paragraph of the chapter about a 40% margin in the WFD footprint. 
     8.  It seems that the seeing numbers in this bullet contradict those in bullet 4.  What am I missing?
     9.  This bullet is largely redundant with bullet 6. 

Page 23, 'The analysis of metrics designed for time-domain science has not yet been performed..."  Is this still true?  The section goes on to discuss SN-specific metrics; this probably belongs (or at least should be cross-referenced to) the SN cosmology discussion.  

  Special proposals: the fact that these different programs are strawmen needs to be made clearer, and earlier on, probably in Chapter 1. 

  Figure 2.7 shows the inter-night gap, so this doesn't include the repeats within a given night.  I think we need to show a histogram of the distribution of time differences in a given night as well. 

  Page 26, end of Section 2.2: can we give rough numbers of how much the western bias affects the seeing and depth. 

  The sky brightness problems here are claimed to make the z and y bands 0.5 mag too shallow.  But earlier you said the discrepancy was more like 1 mag. 

  Section 2.3.  I would start with an overview of the different experiments you have done, so the reader has a sense of where this is all going. I would suggest similarly ending this section with a coherent list of experiments still planned.  (There is such a list at the end of Section 2.4.7, page 44, but this is specific to rolling cadence).  

  minion_1012: "Formally 90% of observing time...".  You say earlier than the number is 85%.  
	  Conclusions, "Althogh the sky coverage ... is 18,000 deg^2, their cumulative area is 22,000 deg^2."  I simply don't know what this means; what is the distinction you're making here? 

  minion_1020: Most readers will not understand why this is called a Pan-STARRS-like cadence.  Another sentence is needed stating that Pan-STARRS' 3PI survey tries to maximize sky area. 

  Figures 2.11 and 2.3 are meant to be directly compared, but their color scales are different.  They should be the same. 
And it would be good to see histograms with Figure 2.11 . 

 enigma_1282 (page 31): Analysis results, there is a redundancy between the first sentence and the sentence, 'In particular, even "no pairs" simulation...."

Note the typo in the following paragraph, search for 'autoreffig' . 

  Figure 2.13: label these with the names of the runs each curve refers to (and as above, rationalize those names).  

  kraken_1053 (page 35), conclusions.  There are other consequence of a longer exposure time, including saturation at fainter mags, worse bleed trails and scattered light from bright stars, more trailing of fast-moving asteroids, etc. 

  kraken_1045: is the pedagogical footnote #7 really needed? 

  kraken_1059: there is mention of the "baseline NE spur", but it was unclear to me what the point of this detail was. What was in the back of your mind for this one? 

  In the same spirit, minion_1022 (relaxed airmass limit): This seems like a bad idea from the beginning; what was the rationale?

  minion_1017 (page 37): There sky coverage of the survey must be smaller with this restriction, no?  There must be regions of the sky that are simply unreachable.  This needs to be mentioned.  

  Table 2.1 (page 38): This sort of summary table should either be expanded to include many more of the runs shown here, or simply dropped. 

  Section 2.4: I found the rolling cadence discussion to be very interesting indeed.   Only a few comments: 
    Section 2.4.2, second paragraph (page 39): among the rolling cadence basics is the *area* that is being observed in enhanced mode at any given season.  I think this is directly a function of the number of samples and the enhancement factor, but it is the way most people think about this, so should be explained and quantified. 

  Section 2.4.3 clearly needs to be fleshed out. 

  Figure 2.16 doesn't quite make sense to me.  The 10-year survey in both cases is highly non-uniform; why is that? 

  Top of page 42 almost sounds like movie mode; this should be described as well. 

  Section 2.4.7: it is my understanding that there is still significant code development needed in OpSim to fully implement rolling cadence.  Is that the case? If so, this should be explained. 

  The list of future metrics on page 43: make sure that none of these metrics are included in future chapters... 

				And that's it!

							Thanks,  Michael

**Comment by AshishMahabal** [comment]
Sections 2.1 and 2.2 looks good indeed.

Some comments (most of these can be ignored and in general are not critical):

(1) Can some details of difference between the three swiss-cheese cadence be added?

(2) First line of 2.2: provide code version number for OpSim3.61 if easily available.

(3) For minion_1016, do we have max number of filter changes in a night? Many other details are given, so this information will make it complete (could be done uniformly for other simulations at some point as well).

(4) Just before the start of 2.3: For the proposals that complete in 3-4 years, will it hurt the proposals if they are spread out? Which proposals are these?

(5) Is there a plan to increase the moon avoidance angle (in future simulations)?

(6) The unrequested and unnecssary revists, do we know what fraction? is the third visit in a different filter? Young transients section (6.2) recommends that.

In #2.3 there are a couple cross-refs missing. Perhaps they have already been put in in a newer version:
(a) Details of the impacts on Solar System science is left to ??, in particular the impact on completeness is evaluated in Section 3.2.
(b) Caption of Fig 2.13
