### ISSUE TITLE
Feedback on the Solar System Chapter

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#426]
@davidtrilling You suggested that we ask Mike Solontoi and JJ Kavelaars for feedback on the Solar System chapter. I will look up their email addresses and point them at this issue, and ask if they can help us out!

What we are looking for at this stage is the following:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (eg Sections 3.2 - 3.7 inclusive) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

When I come to review a science section, these 4 questions are what I will be asking myself as I read it - and if I find any of the pieces missing, I'll write an issue asking for them. Likewise, if anything needs cleaning up, explaining better, or otherwise fixing, I'll issue those things too. It would be great if Mike and JJ could do the same: I'll find out if they are familiar with GitHub. Thanks for the suggestions!

**Comment by drphilmarshall** [comment]
Emails sent, waiting to hear back.

**Comment by rhiannonlynne** [comment]
JJ Kavelaars - @ijiraq 
Mike Solontoi - @solontoi

**Comment by drphilmarshall** [comment]
Thanks @rhiannonlynne :-)

Mike, JJ: you can read more about what we're looking for from you in the [top comment on this thread](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/426#issue-156555444). We're trying to get each section reviewed by June 3rd - hopefully you'll enjoy reading the chapter, and can make some quick comments for the editors to respond to. Feel free to start new issues as you need them, that could be a good way of claiming the sections that you each want to focus on, for example. Thanks for helping out with this!

**Comment by drphilmarshall** [comment]
@solontoi, @ijiraq : apologies, I just noticed that this thread does not yet contain a link to the PDF file itself. Please use this one:

https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf

It's a stable version - the master branch of this repo is still being worked on, and sometimes the auto-compiled PDF linked from the README fails to build.

@solontoi tells me that he is going to start with Section 3: thanks, Mike! As long as you are logged into GitHub you should be able to start new issues to request changes from the writing team. If you direct the message in the body of your issue to chapter editors @rhiannonlynne and @davidtrilling, they will be able to deal with it (either by making the change you suggest, or delegating it to one of their team). At this point there's no need to fork the repo and edit the files themselves unless you really want to.

**Comment by solontoi** [comment]
@drphilmarshall - sorry I switched "chapter" and "section" in my e-mail, didn't mean to say that I was going to focus on 3.3, although I'm certainly going to go over it.

**Comment by drphilmarshall** [comment]
Ah, OK - great! It'll be good to get an overview by looking through all of
chapter 3. Thanks again!

**Comment by bethwillman** [comment]
Overall this chapter is looking good.  Would benefit from some text tightening and addition of details so that community members can understand the assumptions that went into the calculations.  Some specific suggestions:

1. Intro and a few other places could use some references

2. Section 3.2.1 - A title like "Discovery Criteria" could be more descriptive.  

This section as written could use light tweaks to clarify that you will investigate the efficacy of small body discovery given a number of different discovery criteria scenarios instead of "just" describing different examples of detection criteria.  I got hung up on this when reading.

"An optimal discovery strategy for moving objects..." -> "Our investigations (Juric/Jones/Ivezic et al, in prep) have shown that an effective discovery strategy for moving objects..."

The point about the 92% fill factor - This should be relevant for all of the studies in this white paper, right? This statement made me wonder whether everyone included this in their metrics.  Other chapters (and/or the Introduction) should be clear about whether or not they accounted for the fill factor.

3. Section 3.3.2 - What simulated catalog of objects was evaluated for possible detection completeness?  What spatial, magnitude, and orbital distributions for each population assumed?  How is the depth in a given optical filter connected to the H magnitude?  The assumptions should be listed w/ references provided.

4. Figure 3.3 - Instead of three panels with the same title, could remove the hard-to-read legend on each panel and title the panels "NEOs with H < 22.0".  The y-axis already has "completeness" on it.

5. Section 3.4.3, 3.4.4 - How reasonable is the assumption that observations of a given, discoverable, Solar System body obtained years after the first observation, will necessarily be linkable to the correct Solar System body?

7. Sections 3.5.2, 3.5.3 - What assumptions, including activity properties, went into the MBA sample used to do these calculations?

8. Figure 3.5 caption and Section 3.5.1 - there are rogue ??? in the text
