### ISSUE TITLE
Feedback on the Galaxy Chapter intro, further work etc

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#430]
Hi @lundmb - as part of our internal review, would you mind taking a look through the Galaxy chapter and giving some high level feedback, please? The sections are out for focused review already, but I think it would be good to get your impression of the chapter as a whole. Does it hang together well? Are there any pieces you feel are missing, having read it through?

Thanks for helping out with this! @willclarkson and @akvivas will see your comments in this issue thread when you post them, and can act on them as soon as you do. I pushed the deadline for the internal review back to June 3rd so you've got a week or so, but the sooner you get back to them the sooner they can address your feedback and finish the chapter ready for submission. Thanks! :-)

**Comment by lundmb** [comment]
I'll get on this in the next 2-3 days.

**Comment by drphilmarshall** [comment]
Thanks, Mike! :-)

**Comment by willclarkson** [comment]
Thanks @lundmb ! Two-three days works well, we may have some more microlensing material to go in there in the next 1-2 days.

**Comment by willclarkson** [comment]
Hi @drphilmarshall (cc @lundmb and @akvivas ) - what's the cutoff deadline for any updates to the WP at this point? 

From the discussion with the microlensing experts, I now have a prototype microlensing figure of merit worked up in a maf-friendly way, that could be written up for insertion into WP chapter 4. However, I probably wouldn't be able to add it before the June 3rd deadline (possibly *on* the 3rd if I postpone some other tasks this week). 

So - is June 3rd the last date for any changes to make it into the arXiv version? What happens to changes committed after the 3rd? I guess what I'm really asking is, should I sprint now to get the microlensing FoM into the version this week, or do I have longer? 

Thanks, sorry if this is re-treading an issue or message already issued!

**Comment by lundmb** [comment]
Sorry about the delay on this, I think I'm still just in under the deadline on this, barely.

Introduction: This may be sufficiently covered elsewhere in the paper, but I'm approaching this as someone primarily looking at this section. In the second paragraph of the introduction, the current limitations of the galactic plane are only somewhat referred to. It may be more beneficial to be explicit regarding how long the observing will run for (the text currently says that it would end a few years early) and I'd think also discussing what the actual cadence is. I know it's only a few hundred visits instead of closer to 1,000, but I don't know how those visits are going to be spread out in time, and that's going to be very relevant for the science examples discussed (e.g. microlensing requiring observations every few days). The shorter baseline is a limitation, but it may not be the only relevant limitation based off of some of the cadence requirements that are discussed.

Section 4.2.1
There's some varied science cases in there, and it seems like it would be helpful to include some relevant time scales for different science cases. e.g. the second case, novae, talks about needing cadences that are useful for studying them, and that seems partially dependent on the time scale of a white dwarf nova event. Including what the time scales are of the events themselves would add clarity when the suggested approach is to have a cadence that is suited to finding these events, and just an order of magnitude value would be helpful (hours/days/weeks/etc)

Section 4.2.2
Would be useful to outline at this point which figures of merit have already been created and evaluated

Section 4.3.2
Very minor point, but hour angle is mentioned as something that has to be calculated; is it worth noting that MAF already can calculate this, so that's not a step that has to be freshly developed?

Broad chapter question: for the sections following 4.2, which cases are going to be effected by the cadence limitations of the plane? Example, in 4.4.3, studying the bulge is mentioned, and it seems like that would face the same issues as the plane. It may not take much to clarify, but are the examples discussed outside of the section on the plane limited by those same constraints, unaffected, or marginal?

My comments on 4.3 and 4.4 are much more limited, although I think that's in part because the time scales vs cadence thing doesn't seem to come up for those cases as much as what 4.2 is grappling with. Overall the flow seems solid.

**Comment by willclarkson** [comment]
Thanks @lundmb !! cc @akvivas 

@drphilmarshall - do we now need to get these comments addressed by Jun 3rd? 

Best -- Will

**Comment by cbritt4** [comment]
Just to note, the timescales of transients like novae and dwarf novae are also discussed in 6.6.2.

**Comment by willclarkson** [comment]
@cbritt4 -- thanks! I think a reference to that section would address @lundmb 's first point above.

@lundmb - I'm next going to have a chance to work on this in about five hours from now. If any more comments occur to you before 6pm EDT, feel free to write them into this issue thread.

**Comment by willclarkson** [comment]
Hi @lundmb - I think I've addressed about all of your comments that I'll be able to get to today (06/03). The ones I didn't get to were the discussion of the timescales of interest, and the broader discussion on other cases also sensitive to duration and cadence. 

The former I think could be addressed with a table showing typical cadences (like I think the Transients chapter has), the latter I would expect to come out in the figures of merit anyway - but I agree should be summarized somewhere. I suspect that may be best done once more of the FoMs have been evaluated.

Thanks!! -- Will 

cc @akvivas @cbritt4 @caprastro @chomiuk

**Comment by bethwillman** [comment]
I tightened the text at the beginning of the chapter and also have a few detailed comments, for now:

Section 4.2 - Should clearly state that variable sources being considered will be ID'd and photometered by difference imaging, so they can still be studied (albeit with reduced photometric and astrometric precision) in confused regions.

FoM 3.1 - How good is the assumption that a proto-SN *detected* before it goes off will also be  *distinguishable* from the rest of the transient/variable population as a proto-SN that requires follow-up?

There seems to be tension between the fact that minion_1020 is more effective at Galactic SNe discovery than astro_lsst_01_1004, and all of the text devoted to concern about the number of GP visits and their temporal spacing.  This tension should be addressed.

Many figures in Chapter 4 have axis labels that are too small to read and, in places, numbers on axes that are overlapping and illegible.  The figure titles often aren't understandable on their own b/c of jargon. The end-of-chapter placement of the figures makes it difficult to follow the results of the analysis.

4.4.1 - The dust section seems out of place - there are no specific statements about how it relates to the observing strategy, and dust is already discussed in the science book.  This subsection should be commented out for now.

I suggest that a brief summary Section 4.5 is added after the current "Future Work" section - Its currently difficult to understand the key conclusions from this chapter.  A Section 4.5 would be an appropriate place to list the ideas currently given in Section 4.4.3.  The Future Work section could then be named Mapping the Milky Way halo.

**Comment by willclarkson** [comment]
I *think* all the above comments were addressed (since June 4, 2016) so am closing this issue. Thanks all -- Will
