### ISSUE TITLE
Feedback on Young Transients Section 6.2

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#432]
Hi @AshishMahabal   Would you mind taking a look at Section 6.2 of the Transients chapter, and giving @fedhere and @svalenti some feedback, please?  I pushed the internal review milestone back to June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (eg Sections 6.2, 6.3 etc) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of the pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or just comment on the current version in the `master` branch (no-one is editing this section right now). Pull requests would also be warmly received, I expect! :-)

Thanks very much for your work on this!

**Comment by AshishMahabal** [comment]
Will do

**Comment by drphilmarshall** [comment]
Thanks! :-)

**Comment by AshishMahabal** [comment]
Will be talking tomorrow (Thu) to Stefano/Fed to understand a few things that are not clear to me. Meanwhile here are my brief comments anyway.

1.	Does the chapter tell a coherent story about the science that is being planned? 

In each subsection it is kinda assumed that the science is important - and perhaps that is OK. It seems to be the nature of the white-paper to talk of bits and pieces in terms of metrics and observability.

2.	Each science section (eg Sections 6.2, 6.3 etc) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly? 

There is discussion of the need of a somewhat different cadence but there isn’t quantitative evaluation of (all) the existing metrics. Thats partly because of the missing machinery and within those limits, the work is adequate. It may be good to state that explicitly though. 

3.	We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the OpSim operations simulator. Some science sections will contain metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented?

A more detailed plan for future work will be useful. Here for instance about connecting templates and the existing OpSim runs. 

4.	We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

I do not think we are currently in a position for authors to have read other sections and commented on how their proposed strategy will affect science for other groups. That meta-discussion (and evaluation) will stay a bit difficult until more evolved versions of such analyses are available.

There is some more minor nitpicking which I will post after the discussion tomorrow. Others should feel free to join. Will happen between 12 and 2 or 3 and 5 PT. Will post time once its decided.

**Comment by AshishMahabal** [comment]
Thank you Fed/Stefano for the call.

Just for completeness, generating new issues with your names.
