### ISSUE TITLE
Feedback on Supernovae Section 6.3

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#433]
Hi @jhrlsst   Would you mind doing some section reviewing, please? It would be great if you could take a look at Section 6.3 of the Transients chapter, and give @fedhere some feedback. It'd be really good to make sure that the transients and cosmology chapters' treatment of supernovae are well cross-referenced. I pushed the internal review milestone back to June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thanks very much for helping out with this!

**Comment by jhrlsst** [comment]
OK. I will do this. But I will let you know the time schedule as soon as I finish SN cosmology section.

**Comment by jhrlsst** [comment]
It was not easy to review this subsection by itself without reading the entire Section 6.
I tried to quickly read the Section 6, but it is possible that I may have missed some facts. 

1. Does the chapter tell a coherent story about the science that is being planned?
->I believe that this chapter address all types of supernovae while chapter
9.3 focuses on SNe Ia since they are used to probe cosmology. This
Section seems to mainly focus on SNe Ia including a system of SN Ia with
shock (for example, Figure 6.6 and 6.7) which is a specific case of SN Ia
science case. The material is fine, but it will be complementary if the
same types of figures and discussion for core-collapse SNe (e.g. SN II) are
included.  In addition, there are cases of interacting SN II (Margutti et
al., 2014, ApJ, 780, 21) which can be considered at the same time with interacting SN Ia cases.
Many of core-collapse SNe science case may be possibly added by inviting more
experts in the fields (in future maybe).


2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, 
including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?
->  Science case:  In order to be able to recognize interacting SNe Ia, 3
visits per day are requested. Table 6.4 shows comparison between baseline
Cadence and 3 visits. It is not clear what those numbers are. What are 3
and 6? What are ">12"?  Discussion of this comparison is needed. In conclusion,
how many interacting SNe can be identified with triple visits and baseline strategy,
respectively? Or since iinteracting SNe could not be sufficiently identified, are follow-up
observations required in the end? (this, once more, highlights the
importance of prompt identification and classification: for SN Ia this
likely with limit this work to objects that could be identified
spectroscopically, enhancing the important of follow-up).

Perhaps if Figure 6.6 can show both cases of minion_1016 and enigma_1281, the
comparison between baseline plan and triple visit plan may be clear.

3.    We are working towards calculating Figures of Merit given various simulated observing strategies, 
captured in the output databases of the OpSim operations simulator. Some science sections will contain metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented?
-> The analysis results are somewhat confusing. Please clarify the numbers in the tables and figures. 
It is not clear what the numbers of 30 minutes, 2 hr and 24 hours are in Figure 6.5 and why those numbers are chosen. What are implications of Figure 6.5? It seems to show period of variability, but more explanation needed.

We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. 
Is this provided, and does it make sense?
-> Clarification of writing  (I know it is the first draft) is needed in many places.
With current text, it is not clear how much new Cadence (triple visits) will help 
the authors' science goal. Or still spectroscopic follow-up is required to find SNIa 
interacting system with a shock.Clear statements are needed.
