### ISSUE TITLE
Feedback on the AGN Census Section 8.2 

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#437]
Hi @rhiannonlynne   Would you mind doing a spot of section reviewing, please? It would be great if you could take a look at Section 8.2 of the AGN chapter, and give the writing team ( including @ohadshemmer @gtrichards @cmp346 @nielbrandt @AstroVPK ) some feedback. Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or you can just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thanks very much for helping out with this! :-)

**Comment by rhiannonlynne** [comment]
Will do.

**Comment by drphilmarshall** [comment]
Thanks, Lynne! :-)

**Comment by rhiannonlynne** [comment]
_Does the chapter tell a coherent story about the science that is being planned?_

I was only asked to review the section, not the overall chapter. However, I peeked through the rest of the chapter and it seems that while there is definitely a coherent overall theme, the different sections seem a bit disparate. To some extent, this is natural -- each chapter lays out an area of science, while each section investigates in depth a particular aspect. However, I would suggest that (in this 8.2 section or in the introduction in particular) some forward reference could be made to the various sections, suggesting how they relate to each other. 
For example, section 8.2 could be presented as generating the sample of AGN that each of the other sections will investigate particular properties of in more depth  (if this is correct .. it seemed like the other sections might just be investigating a subset of the AGN discovered in the DD fields, while section 8.2 describes how AGN could be discovered throughout the whole survey - a few words explaining this and covering why the DD fields present an interesting subsample but that the entire sample matters as well would be useful). 


_Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?_

There are a few figures of merit that are applicable to this section, 8.2.
The basic goal of the section is to describe how AGN would be discovered in LSST (what their selection criteria would be) and what the resulting census of AGN should look like. Then various techniques for how AGN could be selected are described and matched against proxies for metrics (it doesn't seem that explicit metrics are well defined except for the depth in y band -> expected number of z>6 quasars).

It would be helpful if the selection criteria were described in more detail (astrometric redshifts from DCR is not clear to me, for example, and the method of selecting AGN via color and variability is not described -- if a final method is not known, but a preliminary guess at what that would be is known, perhaps that could be described with that caveat?). The subset of AGN with z>6 is included in this section, but could actually reasonably be moved to a different section, I suspect. 

My suggestion and interpretation of the current sections (provided here merely to try to jumpstart things - if it doesn't make sense, do something else!)
* 8.2 = selection and census of all AGN 
  * add more discussion of how AGN can be selected .. what are the characteristic time scales you expect to need for observations to determine color and temporal variability? what does it mean to determine astrometric redshift - and how does this relate to DCR? are these actually two separate methods, which could have different metrics and final 'census' counts (and maybe end up in separate sections), or are they inter-dependent methods?
  * if these are not mapped to metrics specifically yet, just describe how they would be mapped. This would probably come pretty close to the description of how AGN would be selected, above.
 * would a reasonable final 'figure of merit' be simply the number of AGN discovered with LSST? are there other considerations that need to be included, such as the number as a function of redshift? If so, please add some description of how we could look at these figures of merit - do we need to understand more about the quasar redshift distribution, or is a simple model sufficient? 
* 8.3 = selection and census of AGN with z>6
  * this seems to be based simply on the depth in the y band, but it wasn't clear if this really is simply the maximum single image coadded depth? Or average single image coadded depth? Are there other requirements, such as the requirements for selection that would be implied by the color and time variability detection requirements? 
 * similar comments as above on the figure of merit. 
* 8.4 = studying AGN time variability in detail in the DD fields
* 8.5 = studying AGN size and structure with microlensing 
* 8.6 = future work
* 8.7 = discussion of overall chapter goals


_We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the OpSim operations simulator. Some science sections will contain metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented?_

The single image depth in y band, to estimate the number of high-z AGN, is based on enigma_1189, so should be updated to the current reference run. 

_We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?_

Not provided. 

_If you find any of these pieces missing, it'd be great to write an issue asking for them; likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too._

Not done yet.

**Comment by ohadshemmer** [comment]
Thanks for the feedback @rhiannonlynne 
I'll get to it within the next couple of weeks.
