### ISSUE TITLE
Feedback on Cosmology Supernovae Section 9.5

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#445]
Hi @svalenti  Would you mind doing a spot of white paper section reviewing, please? It would be great if you could take a look at Section 9.5 (supernovae) of the Cosmology chapter, and give the writing team ( including @MichelleLochner @jhrlsst @rbiswas4 ) some feedback. Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:

1. Does the chapter tell a coherent story about the science that is being planned? 

2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  

3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 

4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. The goal is for the various science sections of the white paper to be somewhat homogeneous in style and structure - you might find it helpful to compare this section with 9.4 and 9.6, for example. 

You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or you can just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thanks very much for helping out with this! :-)

**Comment by svalenti** [comment]
Hi Phil,

this is bad timing for me. I will not be able to take a look before June 
2nd, but I will do what I can .

cheers
s.

**Comment by drphilmarshall** [comment]
OK, thanks for letting us know, Stefano. I'll try asking Iair as well.

**Comment by drphilmarshall** [comment]
Hi @arcavi !

Would you mind doing a spot of white paper section reviewing, please? It would be great if you could take a look at Section 9.5 (supernovae) of the Cosmology chapter, and give the writing team ( including @MichelleLochner @jhrlsst @rbiswas4 ) some feedback. Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-) I asked @svalenti as well at the start of this thread, but unfortunately he only has very limited availability. I hope you can step in and help out!

What we are looking for at this stage is to address the following questions about each science section:

1. Does the chapter tell a coherent story about the science that is being planned? 

2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  

3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 

4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. The goal is for the various science sections of the white paper to be somewhat homogeneous in style and structure - you might find it helpful to compare this section with 9.4 and 9.6, for example. 

You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or you can just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thanks very much! :-)

**Comment by jhrlsst** [comment]
I am still updating the supernova cosmology section with Rahul and Michelle. The current text is not convincing enough for new cadence. We are making the justification stronger. I appreciate if you can give us another week to finish up the chapter.

**Comment by svalenti** [comment]
1) Does the chapter tell a coherent story about the science that is being planned?

Yes, the chapter tells a coherent story. The use of light curves of supernovae to do supernova cosmology is clear. A bit less clear is how we will get the Physics of SNe from supernovae light curve poor sampled. The use of SNe IIP is mentioned in the introduction, but not mention in the analysis.  Maybe it would be useful to mention if the number of observations needed to do cosmology of SNe IIP is the same than Ia

2)  Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?
 
There is a clear statement that  a rolling cadence is needed, but the only cadence that is explored is
Enigma-1189. Since this is not anymore the default cadence, I would suggest to use minion_1016 instead or at least to mention in the test the difference between those.
The number of detections may increase if ve use  Kraken_1043 (based cadence with no pair). Maybe this cadence is an option for supernova cosmology, since should increase the number of visits per object. I think it is important to maybe mention it.

3) We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the OpSim operations simulator. Some science sections will contain metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented?

A metric is defined and it is based on counting the number of detections within 50-100 days.  Using this simple metric the need of a rolling cadence is clear. 
I would suggest to try to elaborate more the following sentence or to add a reference: 
“A well-known rule of thumb for good quality SN light curves is to demand 7-10 epochs per light curve spread over 50 days or so for more than one filter.”

4) We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

Yes it is provided. The suggestion of a rolling cadence makes sense. The suggestion of changing the filter every night also make sense but I have the impression that is not discuss in detail previously. Maybe it would be worth to mention if this point will be investigate in the future.

**Comment by jhrlsst** [comment]
@arcavi 
Thank you very much for your comments. We have added about 1-2 pages which takes care of a number of comments.  Most of the version remained the same (the version you have read), but we have added a justification of needs and a little more about rolling cadence. We will make new draft available coming monday and tuesday.

Jeonghee

**Comment by jhrlsst** [comment]
We did implement all comments raised by @svalenti.
Please check the new version and If we miss anything, please let me know.

**Comment by MichelleLochner** [comment]
I believe we've addressed all comments for this round of editing.
