### ISSUE TITLE
Feedback on Cosmology Strong Lensing Section 9.6 

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#446]
Hi @rbiswas4  Would you mind doing a spot of section reviewing, please? It would be great if you could take a look at Section 9.6 (strong lens time delays) of the Cosmology chapter, and give the writing team (i.e. me!) some feedback. Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread.

You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or you can just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thanks very much for helping out with this! :-)

**Comment by rbiswas4** [comment]
Sure .. will do.

**Comment by drphilmarshall** [comment]
Thank you! :-)

**Comment by rbiswas4** [comment]
@drphilmarshall This looks good. I had not realized about the format till I read the instructions !

###  Does the chapter tell a coherent story about the science that is being planned?

Yes. 

### Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?

Yes.  
- Is the cadence going into the formulae the average cadence? In the absence of more information, I am assuming that this is the case for the rest. 
- It may be nice to try to combine cadence with SNR, as by itself, cadence is not a very physical variable. For example if you tried to compare two surveys with different exposure times, or if LSST decided to allow for variable exposure times, this would be crucial. Depending on the time scale of a transient, I think this may be important in treating the difference between cases like two realizations of the same average cadence, with and without pairs/quads.

### We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the OpSim operations simulator. Some science sections will contain metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented?

Yes. I have a few comments on this part of the text
 Section 9.6.2 : Eqns of the model from Liao
- The set of equations might deserve a number
- I wonder if you could change the name accuracy and precision metric to something else like maybe bias and variance/width which have a clear sense of whether high or low values are preferred and/or specify the sense of the metric (high is better or low is better). 
- The models have some interesting effects: in your approximation, the cadence has no effect on the accuracy, but season length and campaign length do! Am I interpreting this correctly that for the usable sample fraction, a smaller campaign and worse cadence is better, but perhaps the precision goes bad? So, in what sense is this a usable sample? This does not seem to agree with the penultimate paragraph of Sec. 9.5.2 (which is what I would have naively expected), maybe because there are some constraints here.
- From the magnitudes on the plots, it seems that the accuracy is much smaller than the precision, so, accuracy is not a worry if they are reasonably uniform. Is this the conclusion I should take away or is the stacking  hiding the fact that the objects which contribute to the accuracy may come from low precision objects? 
- In calculating the metrics, the cadence in the power law used is the mean cadence in the OpSim field over the campaign length: Is this correct? In that case, removing pairs of observations will not improve the evaluated metric (point made in discussion section) since the total number of observations will not necessarily improve. So, is the statement being made that the data challenge would have a different distribution of observations if there were no pairs, and this would change the model itself (and make it more uniform)?
- One thing that is notable in the figures of the metric is that we cannot make out the Deep Drilling fields, even though they have roughly ~25 times as much time spent than the WFD. Not just intuitively, using the formulae in the models, one would expect this to be more that a factor ~ 10 in precision. Is it the color scale/ plot method that is hiding this  or is there a good reason this should not be reflected. 


### We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

Yes. 
The only comment I have on this is the one that factored into the previous section: If the metric is based on average cadence only, will it be able to see the differences due to changing pairs/ rolling cadences etc. 
### Target section

- Has not the time delay of the famous SN Refsdal been measured? Perhaps it should not be included as this is much more about galactic lensing rather than cluster lensing?
