### ISSUE TITLE
Feedback on Special Surveys Chapter

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#447]
Hi @yoachim 

Would you mind taking a look at Chapter 10, Special Surveys, as part of our internal review, please? It's currently missing a section on the Magellanic Clouds, which I am tasked with providing as part of #184, but the other two sections (Solar System mini-surveys and Short Exposures) are there already. 

What I'm looking for is feedback for the writing team ( @dnidever , @knutago and me) on whether this chapter makes sense to you, the reader. Is it clear how these surveys are being investigated, following the procedure of written proposal (in this chapter) to proposed OpSim run (on the GitHub repo) to actual OpSim run to ensuing analysis? Do the sections explain clearly what is needed in each special survey, and why? Do they describe the metrics (either specific MAF metrics, or general types of metric) that will be used to evaluate the surveys once they are simulated? Do they discuss potential tensions arising as a result of each special survey being implemented (such as the cost, in fractions of the total visits, or the hogging of observing time in some way). I think you'll find it an interesting read! 

It would be great if you can post high level feedback to this thread, and open separate issues on things that are obviously missing or problematic. Pull requests are also welcome of course ;-)

Thanks very much for your help with this!

**Comment by yoachim** [comment]
Sure. Can you give me a deadline (that is >= June 3)?

**Comment by drphilmarshall** [comment]
Marvellous. I choose `deadline = 'June 3'` :-) Thank you!

**Comment by yoachim** [comment]
@dnidever @knutago @drphilmarshall 
Here are my comments on Chapter 10.  

Overall:
These are all interesting projects that clearly need an LSST-like facility to work.  The sections are a bit heterogeneous at the moment.  It might help to impose a bit of order and have each proposed project summarize the main science outcomes that can’t be achieved with the baseline and how much time it would take away from the main survey? Bullet lists are nice.

Specific comments:

10.2:
     “sociological” —> “geopolitical”?

“support two important scientific investigations”, is followed by 3 bullet points.

There’s an xxx-note to fill out mini-moons.

Impactors has an xxx-note.

“survey the opposition patch”—> how much area are we talking about?  One field, 10 fields?

semi-random aside, there are clearly a lot of competing constraints/optimizations around the ecliptic.

Measurements:  Here it says the surveys should be in r, but above it says the twilight should be in z.

10.2.3:
While these aren’t in the current OpSim, this would be a great place to drop in a metric result showing how many mini-moons or 1m impactors would currently be discovered, even if that number is zero.

10.3.1:
I of course must point out we now have a sky model that includes a semi-analitical fit to the twilight sky brightness.

10.4:
This object is in the North Ecliptic Spur, right?  That’s good, because if it wasn’t it would be hard to include in the ubercal photometric calibration.  Here, I made a rough little map and put a dot where I think it is:
https://github.com/yoachim/ScratchStuff/blob/master/sched_region_define/M67.ipynb
So we clearly need some “open cluster metrics”, so we can compare the baseline run with something like minion_1020 that observes up to dec=+15 with the regular cadence.  It would be nice to know if the regular WFD cadence is enough, or if this should be treated more like a DD field with special sequences with filter changes, etc.
Since this is a high-profile target, it might be nice to discuss how the LSST observations will complement other observations.  Something like LSST will get the time domain, some fiber-fed instrument will get spectroscopy, HST/GAIA will get astrometry, etc.
I have doubts about porting Kepler saturated star photometry techniques to LSST—we’re going to actually focus the telescope among other important differences.

**Comment by davidtrilling** [comment]
i think some of these fixes (in the solar system projects) are for me. --david

**Comment by bethwillman** [comment]
I like the examples given in this Chapter.

This Chapter would benefit from a bit more introductory context, e.g. 1. Strengthen the statement that the NES, Plane, and low dec are not in the baseline WFD footprint and so are in the baseline as "Special Surveys" - but the details of these special surveys are TBD, 2. define DDF and present as another type of Special Survey, 3. Point to other places in the White Paper that describe these special surveys, 4. List the additional proposed special surveys that are contained in this chapter (is the Solar System "mini survey" instead of/in addition to/the same as the Northern Ecliptic Spur mini survey that is in the current baseline?  would be good to state this right up front).

Then Chapter would also be strengthened with some consolidation of information about Special Surveys, e.g. I suggest that the Galactic Plane discussion remains part of the MW chapter (and is linked to in this Chapter's introduction, @willclarkson), that the Magellanic Clouds text is condensed and made a subsection of this chapter (@dnidever, @knutago), and that there is an overview of the currently proposed DDFs in this chapter (@nielbrandt, @rhiannonlynne).  A fair bit of the needed text already exists - for example in Lynne's recent community.lsst.org posts.
