### ISSUE TITLE
Feedback on WFIRST Supernovae Section 11.3

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#449]
Hi @rbiswas4   Since the SL section should be easy to review, would you mind please also taking a look at Section 11.3 (WFIRST supernovae), and giving the writing team ( including @rubind ) some feedback? I think you'll enjoy seeing how the synergy with LSST is being explored - Section 11.1 contains the basic introduction to the WFIRST survey. It would also be good to look for how well this section is cross-linked to the main supernova cosmology section.

Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. The goal is for the various science sections of the white paper to be somewhat homogeneous in style and structure - you might find it helpful to compare this section with 9.4 and 9.6, for example. 

You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf). 

Thanks very much for helping out with this! :-)

**Comment by rbiswas4** [comment]
Sure I would be happy to look into this and see how we could coordinate the two sections.

**Comment by drphilmarshall** [comment]
Great, thanks Rahul!

**Comment by rbiswas4** [comment]
@rubind :  This looks quite good.
1. Does the chapter tell a coherent story about the science that is being planned?
Yes. 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?

Yes, I have a couple of comments about terminology (mostly Section 11.3.1)
- Enough visits per filter so that some photometric screening can be done before WFIRST triggers any spectroscopy: Using the usual LSST terminology, Current DDF fields have many visits (a visit is considered 2 X 15 sec exposures) (~ 100 in five filters combined) on a single night. In this terminology, it is possible to have many visits, but only a single night, which means that there would not be much of a light curve shape. On the other hand, there should be good SNR on the color even at early times and you could select SN based on that. 

Can this be phrased either as a requirement on color or light curve shape measurement before WFIRST is triggered ? Said differently when you say visits are you following the LSST convention and saying 20 visits per filter (on the same night) is good enough ?

- the light curve should continue: The way the DDF field strategy works is stochastic, ie. it is not pre-programmed to return to the field at specific times, but on the average the strategy tends to return to a field a large number of times.  Can this be phrased as a requirement of the fraction of the SNe suggested to WFIRST that pass certain criteria?

- Since criteria of quality and classification will probably vary by redshift, could you add something about expectations of the redshift distribution of the 2000 SNe in  Wide (< 0.4) and Medium( < 0.8) that WFIRST would expect?


3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the OpSim operations simulator. Some science sections will contain metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented?

 - I think most of it has been tied to the SN Cosmology section. There are certain additional requirements for WFIRST and I think rephrasing some of the requirements (as suggested in point 2.)  should help us have a clearer plan for a metric calculation.


4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

While the text does not have this format, the content in the chapter has the introductory information at this point and can be put into a closing summary paragraph for the sake of homogeneity.


-----
Typo : 
- Introductory paragraph: would followed -> would  by followed by IFU
