### ISSUE TITLE
White Paper: From Good Questions Come Interesting Conclusions

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#485]
@ivezic You mentioned that you have a set of questions that the OpSim group would like to hear answers to, for each science case. Can you please pose these questions here, as a bulleted list, so that the science case authors can answer the ones that are relevant to them in the conclusions of their sections? The chapter editors can collect them into an executive summary later. Thank you! :-)

cc. @LSSTScienceCollaborations/observing-strategy-white-paper-editors @LSSTScienceCollaborations/observing-strategy-white-paper-contributors

**Comment by drphilmarshall** [comment]
Hi @ivezic ! How's that list of questions coming on? Great if you can have it ready by our meeting next week, so we can discuss them on the call before going off and answering them. Do you need anything from us?

**Comment by ivezic** [comment]
Dr. Phil,
I cc-ed you on all correspondence with the opsim group and (apparently erroneously)
assumed you saw that the list was ready (to be taken). In any, case I am pasting here
the final version:

=======
We invite the editors to consult with their coauthors and consider whether or not and how 
each science topic in their chapter constrains the observing cadence in several specific ways. 
Some of the following questions address relatively simple fine tuning of survey parameters, 
and others offer the possibility of dramatic changes.  It is particularly valuable to identify 
constraints or tradeoffs that hold across a broad swath of science programs, and to understand 
which options, if any, are neutral to the science. Therefore, please help us identify any 
generalization of conclusions that hold for multiple topics or an entire chapter.

If your science would benefit from a cadence methodology not covered by these questions, 
please enter a description of this methodology at http://ls.st/yqq

To illustrate the expected detail level of answers, we also provide an example for each 
question (which attempted to reflect real constraints, but are not binding in any way). 

1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?  

A: Weak lensing science scales with the number of well-measured galaxies. The main
survey area should be optimized to maximize the size of galaxy sample. 


2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling?  For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts).

A: For Type Ia SNe science, light-curve sampling should be about twice as frequent as
for the current baseline cadence. The benefits of this improved sampling would outweigh
the loss of active sky area. 


3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise.

A: The single-visit depth required for detecting RR Lyrae stars to the presumed tidal radius 
of the Milky Way is at least r~24.5. The single-visit depth required for detecting SNe to redshifts 
of about 1, that can be probed with LSST filter complement, is at least r~24.5. The increased 
number of visits that could be obtained with shallower data would not benefit either science
case. 


4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)? 

A: Our science program cannot place any constraints on the Galactic plane coverage. 
 

5) Can you place constraints on the fractions of observing time allocated to each band? 

A: Photometric redshift estimates for galaxies require that each band receives at least 
10% of the total observing time. 


6) Can you place constraints on the cadence for deep drilling fields? 

A: In order to obtain good light-curve templates for SNe, at least one deep drilling field
has to be observed each night in all 6 bands for at least 4 months. 


7) Assuming two visits per night, should they be obtained in the same band or not? 

A: The completeness considerations for asteroids suggest that two visits in a given 
night should be obtained with the same band. 


8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in 
all or in selected bands); a greatly enhanced cadence for a small area.  

A: The deep drilling fields with multi-wavelength data would enable early science results
if LSST data were obtained early. 


9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.? 

A: Weak lensing science would greatly benefit if the r and i band data were obtained during
the best seeing nights. 


10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?  

A: Science programs requiring a minimum single-visit depth (such as Near-Earth Object
survey) would benefit from its uniform distribution. 

=======

**Comment by rbiswas4** [comment]
Hi @drphilmarshall / @ivezic Is this a discussion for the Aug 3 or the Tuscon sessions?

**Comment by drphilmarshall** [comment]
This great, thanks Zeljko. The chapter editors agreed to issue their science section teams with answering these questions as a bulleted list.

**Comment by jhrlsst** [comment]
Here is answer of the question 2.

2) Can you place constraints on the trade between uniformity of sampling and frequency of
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while
maintaining the nominal total visit counts).

A: For Type Ia SNe science, light-curve sampling should be about twice as frequent as
for the current baseline cadence. The benefits of this improved sampling would outweigh
the loss of active sky area.
-> This is true for a short time period (say 60 days), but the loss of active sky area will be made up for a longer period (say 1 year). Thus the final coverage will be the same.  Basically higher sampling cadence we suggest for SN cosmology is to switch the order of observations from the current baseline cadence. 
A simple way to explain is the following. 
we define a total of available sky to be observed  = A+B+C

Current based cadence observes:
A1, B1, C1, A2, B2, C2, A3, B3, C3, A4, B4, C4, A5, B5, C5, A6, B6, C6, A7 ..... 
(in time sequence. The number indicates the number of observations, A1, A2, and A3 are the first, second and third observations, respectively).

Enhanced sampling cadence for SN cosmology observes A1, A2, A3, B1, B2, B3, C1, C2, C3, A4, A5, A6, B4, B5, B6, C4, C5, C6, A7.....
As you can see, the total sum of observations (sky coverage) will be the same as that of current based cadence. Therefore, the uniformity and frequency remain the same when you sum the observation over a year. But if you count only for 2 months, we have a smaller sky coverage (A1, A2, A3 only instead of A1, B1, C1). 

We just want to switch the order of the current cadence observations.The switch is not as simple as what I described because the sky visibility is changed everyday; however, I think it shouldn't be too hard to make new set of observing sequences (that is why we need opsim runs). 

Hope this is clear enough.

**Comment by jhrlsst** [comment]
Bottom line is that the sky coverage and coadded depth remain the same as those of current baseline cadence when we count observations for a year (or longer). However, if you count only for 2 months (i.e. for a short term), the sky coverage is 1/3 but the depth is 3 times as those from the current baseline cadence.

**Comment by jhrlsst** [comment]
We will clarify this in our chapter.
