### ISSUE TITLE
"Bolting things to MAF"/lightcurves discussion

### ISSUE THREAD

**Issue by ebellm** [LSSTScienceCollaborations/ObservingStrategy#496]
Hi @yoachim: at the Tuscon Workshop, @drphilmarshall has encouraged us to discuss(with Rahul and others who are interested) how users can approach more sophisticated analyses using MAF.  

For example, many of us in the Transients working group in particular are interested in working with realized lightcurves in a more sophisticated way than is currently possible.  The general workflow we're looking for would be to simulate a _population_ of events, extract a lightcurve for each event, compute a measurement from that lightcurve, and then aggregate those measurements into an overall metric.

**Comment by jhrlsst** [comment]
Currently, Type II SNe light curves are not included in the white paper (as far as I can tell; if I miss this in the current version, please let me know) we may want to generate SN II light curves,  in order to visit optimal observing strategy for them.

**Comment by yoachim** [comment]
Hi @ebellm,

Yes, that is something that should be pretty easy to do--I think @rbiswas4 managed to drop in his own personal favorite SN lightcurves into the TransientsMetric.  I would say just have your metric include a method for generating your personal favorite lightcurve (or have it call extenal code).  Then the metric run method can do the Monte Carlo work of generating a population of transients and deciding how well each one is observed.  Run it at low spatial resolution to keep the runtime reasonable.  

I can stub out a simple example in sims_maf_contrib if that would help.

**Comment by ebellm** [comment]
Hi @yoachim, 

What I'm wondering about is whether we can get away from repeating lightcurves back-to-back-to-back as in TransientMetric; that's what I suspect puts more stress on the MAF infrastructure.  But let's talk.

**Comment by rhiannonlynne** [comment]
Also consider a user points slicer, where the points are the locations of
the transients. To make it more efficient, maybe we need to figure out
something that narrows down the time range to match in opsim as well, but
we could see if it was necessary first.

**Comment by rbiswas4** [comment]
@ebellm @yoachim 

Replacing the sinusoidal light curve of `TransientMetric` is possible: I think examples of  this have been done by @svalenti and @fedhere in discussions with @yoachim in what is called the `TransientAsciiMetric` https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/mafContrib/transientAsciiMetric.py. I have used that before, but we can also do what @yoachim pointed out and referred to (ie. subclass transientMetric and write a function to replace light curves).  I tried that in
https://github.com/rbiswas4/sims_maf_contrib/blob/SNmetrics/mafContrib/snDiscovery.py which I tried out in
https://github.com/rbiswas4/sims_maf_contrib/blob/SNmetrics/science/Transients/SNDiscovery_example.ipynb
It does use some other software, and I will merge after a few changes and documenting how to install 
the other software.

Replacing the back to back nature of light curves can be done by the `nPhaseCheck` parameter to the metric. This will be back to back realizations of light curves but at uniformly different phases. Obviously, this implies  light curves, so you can expect the computing load to increase.

However, at least as far as I can see, as things get more and more complicated (populations of objects, analysis method) and time consuming as it would in detailed simulations and analysis, it becomes more and more unwieldy to put that into MAF. MAF was written as a tool to do calculations of heuristics of Observing Strategies, and performs excellently at that goal, but is not a great framework for simulations and it is unfair to expect any tool to be good at doing quite different things. This is true, because the basic methods in a metric analysis are reduction/aggregates to a summary statistic, while if you actually produce detailed simulations, you want to have access to everything, and be able to do further analysis.

Finally, for SN Cosmology (and I am sure this is the case with other sub fields too), simulation tools are essential for trying and testing different methods of analyses (even when the idea of providing feedback to the survey strategy does not exist), which is exactly like the description here: 

> For example, many of us in the Transients working group in particular are interested in working with realized lightcurves in a more sophisticated way than is currently possible. The general workflow we're looking for would be to simulate a population of events, extract a lightcurve for each event, compute a measurement from that lightcurve, and then aggregate those measurements into an overall metric.

**Comment by yoachim** [comment]
Yup, I think @rhiannonlynne is right--the two obvious ways to do things are either run a little Monte Carlo at each spatial point, or generate your population and then use the userPoint slicer.  I'll make a toy model of that scenario too.

**Comment by yoachim** [comment]
Here's an example of doing a fancier lightcurve analysis with MAF:
https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/science/Transients/TransientMontewUPS.ipynb

The general steps:
1) write a function that can generate a lightcurve given time and some shape parameters
2) Write a metric that can decide if a lightcurve is observed well enough to count as detected
3) Generate a bunch of objects (ra, dec, time, and shape parameters)
4) put the object properties into the slicer (this is kind of a magic undocumented thing you can do)
5) run it all with MAF
...
Profit!

**Comment by yoachim** [comment]
And here's the notebook that runs a Monte Carlo at each spatial point:
https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/science/Transients/transientMonteMetric.ipynb

**Comment by drphilmarshall** [comment]
Great stuff! Thank you @yoachim :-) I look forward to seeing everyone
profit next week - this looks like an excellent starting point for some
Thursday hacks and discussion.

**Comment by drphilmarshall** [comment]
@yoachim We are now both in Tucson! Let's meet up and talk about what could be useful to do in the hack session on Thursday. A short demo of what you have made possible, followed by some discussion of how best to use MAF, could be useful to many people I think.

**Comment by ebellm** [comment]
@yoachim : those example notebooks look great.  Looking forward to hacking on them on Thursday.

**Comment by willclarkson** [comment]
@yoachim @ebellm -  I agree, those notebooks will be very helpful. I'm looping @caprastro, @chomiuk and @cbritt4 into this discussion, as population recovery through variability is also important to their science (e.g. Chapter 4.2). Cheers - Will
