### ISSUE TITLE
Science Case Conclusions: 9.5 (Cosmology: Supernova Cosmology and Physics)

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#507]
Dear WP section 9.5 team (@MichelleLochner, @jhrlsst, @rbiswas4, @sethdigel ):

Shamelessly copying Will Clarkson's idea and post, I'm issuing the section authors in exactly the same way to collect responses to this. Once we have responses from each section, @egawiser and I can collate them into a chapter summary.

To help produce conclusions in a form suitable for tradeoffs to be assessed, the chapter editors have been asked (issue #494 ) to task our writing teams with providing short (~1-2 sentence) answers to a list of 10 questions produced by @ivezic, about the material in our chapter sections.

I think this is probably best done through this GitHub system, by entering text straight into this "issue." Therefore, please make an attempt at the questions below, by editing this issue text. (There should be a little crayon-like icon on the far right of the blue title bar for this issue - that's the "edit" button.)

To make this process easier, Zeljko has provided sample answers to the questions, which you can find in the original issue #494. Below is the original request text from @drphilmarshall, followed by the questions.

Cheers -- Michelle

"@ivezic would like to know how each science case constrains the observing cadence in several specific ways, and has provided a list of ten questions he would like answered for each science case - his list is below. Not all the questions will be relevant to every science case, but every science case must present its conclusions, and this list of questions is a very good framework to base them on! Some of the questions address relatively simple fine tuning of survey parameters, while others offer the possibility of dramatic changes. It is particularly valuable to identify constraints or tradeoffs that hold across a broad swath of science programs, and to understand which options, if any, are neutral to the science - by having every science case answer these questions, we will be better able to do that.

To illustrate the expected detail level of answers, we also provide an example for each 
question (which attempted to reflect real constraints, but are not binding in any way)."

**1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?**

Our answer comes here:

**2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts).**

Our answer:

**3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise.**

Our answer:

**4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)?**

Our answer:

**5) Can you place constraints on the fractions of observing time allocated to each band?**

Our answer:

**6) Can you place constraints on the cadence for deep drilling fields?**

Our answer:

**7) Assuming two visits per night, should they be obtained in the same band or not?**

Our answer:

**8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area?**

Our answer:

**9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?**

Our answer:

**10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?**

Our answer:

Finally, if your science would benefit from a cadence methodology not covered by these questions, 
please enter a description of this methodology at http://ls.st/yqq

**Comment by jhrlsst** [comment]
OK. Here is my draft of answers for the 10 questions, but I would like to check with SN cosmology group for a couple places I marked as "*" (within 1 or 2 days). Since most of answers are here, I am putting the contents here (instead of white paper). I also think making all these answers in one chapter is better (so one can compare one to the other for the same questions. This will also help to avoid repetition of the questions.

Anyway, here they are:

1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?


For most of SN science, multiple observations with optimal time intervals (which will
result in increases of coadded depth) are important. The current survey coverage
(18,000 sq. deg.) is better than increasing the sky coverage up to ~30,000 sq., since the
latter will decrease the number of sampling of a SN light curve. 
Note that this does not mean that the absolute large sky coverage is not good for SN
study and the large sky coverage can help to study  cosmic isotropy as long as the
quality of light curves is sufficient for SN classification.

2) Can you place constraints on the trade between uniformity of sampling and frequency of
sampling? For example, a rolling cadence can provide enhanced sample rates over part or
all of the survey part of the time, at the cost of reduced sample rate the rest of the
time (while maintaining the nominal total visit counts).


For Type Ia and other SN science, light-curve sampling needs to be about twice or three
times as frequent as for the current baseline cadence. The benefits of this improved
sampling may have to outweigh the loss of active sky area temporarily (if one add the data
less than for 2 months), but over the survey for a year there is NO loss of sky area (see
Section 9.4 for details). In trade of the increasing sampling, we may have less number of
SNe compared with the baseline cadence, and SNe discovered with LSST (WFD) will have
better sampling light curves.


3) Can you place constraints on the tradeoff between the single-visit depth
and the number of visits? Especially in the u band, where longer exposures
would minimize the impact of the readout noise.

*The longer exposures in the u band is not particularly important for SN science. The
number of visits (with optimized time intervals) is more important than the single-visit
depth.

4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal
sampling, visits per band)?

The Galactic plane is not the main interest of SN cosmology and SN science. Main interest
area is galatic longitude greater than 30 degree. 


5) Can you place constraints on the fractions of observing time allocated to each band?

There is no additional contraint to the baseline cadence. A higher number of filter
coverage benefits SN detection, and uniformly distributed coverage of each band benefits
SN science. 

6) Can you place constraints on the cadence for deep drilling fields?

Observing the DDF every night or every the other night for short time (10-15 min) at least
for one band will provide good sampling of SN light-curves. 


7) Assuming two visits per night, should they be obtained in the same band or not?

* Different band coverage of two visits per night is preferred which will help SN classification. 


8) Would your science benefit from a special cadence prescription during commissioning or
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in
all or in selected bands); a greatly enhanced cadence for a small area.

The deep drilling fields would enable early science results of SNe if LSST data were
obtained early. 


9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?

SN science would greatly benefit with good seeing and low airmass since the resulting
images will allow to sepearte SNe from the host galaxies and the ISM structures in the
galaxies.


10) Do you have science drivers that would require real-time exposure time optimization
to obtain nearly constant single-visit limiting depth?

The two images that are used to generate a difference image require real-time exposure
time in order to reduce any other residuals than transients including SNe. Other than
that, the constant single-visit limiting depth is not critical for SNe.

**Comment by StephenRidgway** [comment]
Hello,

Item #10 comments on the need for consistent scaling of images for differencing. Presumably this is a requirement for all difference image science, and would probably require numerical scaling for precise matching of brightness even if variable exposures were activated.  I’m thinking that “no” for #10 would be OK and less ambiguous.

Stephen

**Comment by jhrlsst** [comment]
You may be right. Just simply "no" to the question (10) can reduce any complication of misunderstanding. The project will take care of the difference images.

**Comment by sethdigel** [comment]
The responses look well considered.  I cannot say that I have studied the answers from the other science thrusts but the phrasing "Can you place constraints on" suggested that quantitative statements, or metrics, were being requested.  Easier said than done, of course.

Regarding the response to #6, "Observing the DDF every night or every the other night for short time (10-15 min) at least..." does that mean each DDF?  And 10-15 minutes each?  (Presumably spread out in time).

**Comment by jhrlsst** [comment]
Hi Phil,
I did not realize the deadline is today, and still I was going to wrap up the answers around today so Zeljko can make conclusion. However, DESC-SN team wants to discuss more about this during the group Telecon on next Tuesday. Can I deliver the answers on next Tuesday or Wed?

**Comment by StephenRidgway** [comment]
This discussion will continue throughout the survey.

Remember, “perfect is the enemy of good”.

: )

**Comment by ivezic** [comment]
Yes, next Wed would be ok - but as Steve said, at some point we need to converge!

**Comment by jhrlsst** [comment]
Here are answers from the consensus of DESC-SN working group. (I will include them in the white paper shortly).

1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS) or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?

For supernova observations, the most important aspect is cadence: we need a good sampling of well-measured light curves of supernovae. If the sky coverage can be increased without sacrificing the number of observations per supernova (i.e., over one season), such as using a rolling cadence strategy, this will greatly improve supernova science. Inasmuch as requiring increased sky coverage could negatively affect cadence over one season, our preference is not to increase to a larger sky coverage.



2) Can you place constraints on the trade between uniformity of sampling and frequency of sampling? For example, a rolling cadence can provide enhanced sample rates over part or all of the survey part of the time, at the cost of reduced sample rate the rest of the time (while maintaining the nominal total visit counts).

Frequency of sampling is much more important than uniformity over long time scales for all forms of supernova science. For SN Ia cosmology, light-curve sampling should be about three times as frequent as for the current baseline WFD cadence. While further investigation is needed, a reasonable length of a season with enhanced rates is around 120-150 days. A rolling cadence will allow this improved sampling while still keeping the sky coverage and co-added depth, by concentrating on different fields in different seasons (see Section 9.5 for details). 



3) Can you place constraints on the tradeoff between the single-visit depth
and the number of visits? Especially in the u band, where longer exposures
would minimize the impact of the readout noise.


In general for supernova science, the number of visits is more important to the single-visit depth, though we would not advocate any decrease in single-visit exposure time (below 2x15 sec). The U band  is useful for the low-z (wide-area) sample and and their calibration of the Hubble diagram. It is not obvious if longer exposures are helpful at this time for supernova science.




4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal
sampling, visits per band)?


Our supernova science is extragalactic and will use high Galactic-latitude fields almost exclusively (to minimize Milky Way extinction systematic uncertainties). Survey time spent on Galactic fields takes away from survey time for our science; we would optimize for less time in the Galactic plane.


5) Can you place constraints on the fractions of observing time allocated to each band?


For supernova science, we have no strong preference for any band and would benefit from roughly uniform depth per band. While redder bands are more useful for higher redshift supernovae, the bluer bands are helpful especially for lower redshift objects. 
Therefore, visits in each band should be uniformly spread in time is preferred for WFD. We prefer a higher number of visits to redder bands for DDF.


6) Can you place constraints on the cadence for deep drilling fields?


Our optimal cadence would for the DDFs would be nightly or every other night; every three nights would be acceptable. Beyond this we run the risk of large gaps more than ~7 days, which would be detrimental to supernova science. Ideally, the DDFs would be observed in all available filters, though not all filters are needed every night (so for instance some filters could be observed on night 1, the others on night 2, and repeat). The single-night depth should be 1-2 mag deeper than a WFD field, but not much more; any extra time is better spent on a different night. 

We would like a suitable number of extragalactic DDFs in total so that at least a few (~3 to 5) are being observed at any time in the survey: we would limit an increase in the number of DDFs if it came at the expense of our preferred high cadence. Each field should be observed for a “season” of length at least ~120-150 days, staggering the fields so new fields cycle in as old ones cycle out. In addition, for DDFs, the u-band exposure time could be increased to minimize readout noise.



7) Assuming two visits per night, should they be obtained in the same band or not?


Supernova science benefits enormously from having color information, particularly in discovery and early epochs to help classification. Two visits in the same band will be less useful than visits in different bands.



8) Would your science benefit from a special cadence prescription during commissioning or early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area.


During commissioning, we would like as many DDFs as possible observed in all filters (with few times the per-night exposure time) so that templates can be created for each of the DD fields we consider. This will allow us to find useful supernovae in these DDFs as soon as the survey starts, and provide us with useful time to deal with any issues in the image subtraction etc. before the survey begins. 

Early in the survey, we must build templates for all fields (more broadly than just the DDFs). Our favored method for doing this is to devote the bulk of year 1 to covering the full sky area, with a rolling cadence survey commencing thereafter. As above, the templates should be at least a few times the exposure time of a single visit (so that the template noise does not dominate the subtraction). This is particularly important in the first 3-5 weeks of the survey, to ensure that we get useful data from the rest of the critical first year.


9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?


While supernova observations benefit from good seeing, it is not as strong a requirement as it is for other science cases. Moreover we’d like to limit any image coaddition issues for very good seeing (under the assumption that these remain): we can make good use of observing conditions with slightly poorer seeing.


10) Do you have science drivers that would require real-time exposure time optimization
to obtain nearly constant single-visit limiting depth?

A sufficiently long (or nominal), fixed exposure time should be adequate for supernova science. No real-time optimization is necessary, and single-visit science is not the limiting factor for SNe science.

**Comment by jhrlsst** [comment]
Hi Phil,
I can not push the tex file because of the permission problem.
I haven't updated the files for a few months so the permission is disconnected.
git config --global user.username jhrlsst
[MERAK:ObservingStrategy/whitepaper/cosmology] jrho% git push
remote: Permission to LSSTScienceCollaborations/ObservingStrategy.git denied to jhrlsst.
fatal: unable to access 'https://github.com/LSSTScienceCollaborations/ObservingStrategy.git/': The requested URL returned error: 403

Rahul said he pushed the file, but the file was not updated yet as I can see int the github page.
Are you the one who control the permission?

**Comment by jhrlsst** [comment]
But I see the pdf file is updated. So this is done. The conclusion is updated with answers of 10 questions. 


However, please check the permission issue for me. Thanks.

**Comment by jhrlsst** [comment]
In fact, the file is still not updated. I was confused with the file I compiled. I want to keep the promise of Wed. deadline.

**Comment by drphilmarshall** [comment]
Hi @jhrlsst - I just merged the PR that @rbiswas4 made, containing your conclusions text ( #570 ), so your text is now include in [the latex file](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/Cosmology/supernovacosmology.tex#L883). Rahul submitted this PR from his fork, because he only has "Read" access to the repository. In fact, as of sometime in the fall, only the chapter editors (Eric and Michelle, in the cosmology case) have "Write" access to this repo - we switched to this mode to try to contain the document as we move towards submission. You too should be able to push commits to [your fork](https://github.com/jhrlsst/ObservingStrategy) and submit pull requests from there. Sorry for the confusion!

So: looks like we can close this out! Hurrah :-) Thanks, all!

**Comment by jhrlsst** [comment]
I see that things have changed. You approve one by one. Yes, it is good to close this out.

**Comment by jhrlsst** [comment]
Why did I get that permission issue? Did I miss a step?

[MERAK:ObservingStrategy/whitepaper/cosmology] jrho% git push
remote: Permission to LSSTScienceCollaborations/ObservingStrategy.git denied to jhrlsst.
fatal: unable to access 'https://github.com/LSSTScienceCollaborations/ObservingStrategy.git/': The requested URL returned error: 403

Did you fix the permission today or yesterday? I don't want to test it because it will confuse your end.

**Comment by drphilmarshall** [comment]
Sorry, I should have been clearer. Everyone except the chapter editors had their permissions changed from "Write" to "Read" access, to help contain the modifications to the repo as we get ready to submit the white paper. So, you can't push to a branch on the base repo, but you can push to your fork and submit a pull request from there.

**Comment by jhrlsst** [comment]
I see. Thanks for clarification.
