### ISSUE TITLE
Answer Zeljko questions for Variables and Transients chapters

### ISSUE THREAD

**Issue by StephenRidgway** [LSSTScienceCollaborations/ObservingStrategy#567]

**Comment by StephenRidgway** [comment]
Working on several incomplete answer sets. 
Posted for 6.6.2 CVs, 5.5.2 Planets, 6.6.1 TDEs.
In progress: 5.2 Cepheids, 5.5.1 Pulsating variables.

**Comment by StephenRidgway** [comment]
@drphilmarshall @ivezic This week, incorporated cadence answers into a half-dozen sections in chapters 5 and 6.

**Comment by ivezic** [comment]
Great, thanks! Am about ready to start perusing these additions.

**Comment by drphilmarshall** [comment]
Brilliant! Thanks Steve :-)

**Comment by AshishMahabal** [comment]
There is also older text that people had provided that may not have been fully incorporated. It can be found on this thread: https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/526 

Also, yesterday at the TVS call we reiterated for section leaders to provide further inputs on the ten questions.

**Comment by StephenRidgway** [comment]
OK, great.  

Today was Phil’s requested deadline, and coauthors of the sections I worked on were mostly not aware of the questions or the deadline - some did not know who Phil is.

I guess communications are not perfect.

Steve

**Comment by drphilmarshall** [comment]
Hmm - interesting. I didn't know we had a community beyond GitHub! We
should encourage them to watch the repo, so that they get the email
notifications, but I realize not everyone likes getting all the messages...
The solution to that is to make sure that everyone who is contributing is
in the "Observing Strategy White Paper Contributors" team, so that when we
@mention that team name (just start typing "contributors" after the '@'
sign), they are sure to get a message. The current team membership can be
viewed here: perhaps some of your people are not on this list, Steve?

https://github.com/orgs/LSSTScienceCollaborations/teams/observing-strategy-white-paper-contributors

**Comment by StephenRidgway** [comment]
Paula: szkody@u.washington.edu
and Keivan: keivan.stassun@vanderbilt.edu

with whom I’ve recently corresponded do not seem to be in that list.

Most of the contributors listed in the Chapter 6 header are not on the list, and some of the contributors in the Chapter 5 header also.  But if the list only includes those who have submitted to gethub, maybe that is not surprising.

**Comment by StephenRidgway** [comment]
Hi, I thought that perhaps I could integrate the material here from #526 <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/526>  into the document, but I find that the contributions are kind of “stream of consciousness” and not organized by section so I don’t think I can do them justice.  I suggest that everybody read the draft answers for the sections that interest them and make or propose changes. Zeljko’s last post to issue #507 said that until Wednesday is OK.
