### ISSUE TITLE
Comments on Section 10.4 (M67 mini-survey) from Jason Kalirai (SAC)

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#618]
- I like the core science in this chapter (fundamental stellar astrophysics), but the idea of doing one cluster with LSST seems odd.  The kinds of effects that are being measured are things that will vary with age and mass, so you really want to survey a range of clusters with different ages.  There are other clusters that satisfy the selection criteria (low extinction, well populated, nearby) that could also be added to the science case.  I think building this up to a more comprehensive program offers some advantages.  Otherwise, it seems to be the type of thing that could be done today with Subaru/HSC as a stand alone proposal.

**Comment by drphilmarshall** [comment]
@RuthAngus Here's some thoughtful feedback on your team's M67 section in the LSST Observing Strategy White Paper. Can you please take a look and formulate a response, please? We can use this thread for discussion - and feel free to @mention other people to come join us. Thanks! :-) CC: @ivezic

**Comment by ivezic** [comment]
We need to make sure that the following coauthors are aware of these comments:
Suzanne Hawley, Ruth Angus, Jim Davenport @suzannehawley @RuthAngus @jimdavenport

Please can any of you confirm that you can address Jason's comments before the deadline?

**Comment by RuthAngus** [comment]
Hi all, 

Thank you for these comments and I apologize for the delayed response! I have asked for some feedback from the rest of the group regarding this comment. We agreed that we would like to study multiple clusters however the reason we focused on M67 in the special survey section was because it is very slightly outside of the nominal footprint of the survey and because it would be a great deep drilling field candidate. In the report created for the community-based study back in May 2016 we discussed other clusters. See https://arxiv.org/abs/1607.04302 and https://arxiv.org/abs/1610.01661. @jradavenport

**Comment by drphilmarshall** [comment]
Hi Ruth - Sounds like you should explain that in the text; you cold also
say that this science case could evolve into a DDF white paper, and refer
to the table in the introduction chapter. Thanks!

**Comment by RuthAngus** [comment]
Hi Phil, sure - I'll update the text. What is the deadline on this? I have a busy couple of weeks coming up!

**Comment by drphilmarshall** [comment]
OK, I added Jason's review feedback as a comment in the latex, and added a note in the text based on Ruth's message. The work to extend the science case to multiple clusters needs issuing as part of v2 development - I'll leave that to the section authors!
