### ISSUE TITLE
Comments from Mansi Kasliwal (SAC): Chapter 6

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#628]
#Section 6.2:
- The proposed metric for median time difference between first epoch and last epoch in a given night is confusing - perhaps they meant maximum time difference? 
- A zoom-in to Figure 6.4 right panel may highlight the importance of 1-day cadence instead of 3-day cadence to discover young transients (as the slopes are mag/day).  Add a sentence to answer A2?
- It is not clear why they say that such a search should avoid the ecliptic plane (I would guess the ecliptic latitude is irrelevant). The statements here are confusing.
- The suggestion on deep drilling fields is not clear as there is no calculation of rates to support this statement. 

#Section 6.4
- Fraction of events detected is a good start. But a better FoM should fold in the rates of GRBs to give absolute numbers of detections and constrain the area over which a high cadence is needed. Moreover, identifying an afterglow at very late-time where the delta-mag/delta-hours is small may render it indistinguishable from other transients.

**Comment by drphilmarshall** [comment]
Thanks Mansi (via Michael)!

@fedhere @ebellm Can you please take a look at Mansi Kasliwal's review of the Transients chapter, and address her comments and queries in a PR? Think of it as a miniature referee report! :-) Thank you!

**Comment by ebellm** [comment]
I think the current text in 6.4 mostly covers Mansi's points--I added a minor clarification.  I agree that improving the metrics is important but practically it will need to wait for a later whitepaper version.

**Comment by fedhere** [comment]
@svalenti can you respond to the 6.2 comments and push the changes to the branch where I added the figure master:bianco-ch6-response:

**Comment by svalenti** [comment]
I don't think I agree with the  first comment: 
"The proposed metric for median time difference between first epoch and last epoch in a given night is confusing - perhaps they meant maximum time difference?" 
We do not want to take the maximum time difference between two visits, we are interested in the median time difference between two visits

**Comment by svalenti** [comment]
"A zoom-in to Figure 6.4 right panel may highlight the importance of 1-day cadence instead of 3-day cadence to discover young transients (as the slopes are mag/day). Add a sentence to answer A2?"
Instead of a zoom-in in Figure 6.4, I think figure 6.5 (right panel) is the right point to stress how much one day cadence is important. but, I think we need to change the answer to A2: "Two visits/night is not sufficient - a rolling cadence can provide a satisfactory solution"
with 
"Frequency of sampling is far more important than uniformity of sampling for early classification of interesting cadence. The rolling cadence is definitely the first step to take, but it is still not enough to identify young transients. A longer than .4 hours intra-night gap or, even better a one day cadence would allow young transients to vary enough to be identified. If the second visit occurs on 0.4-hour time scale, a different filter would be preferred (color information can be alternatively used to identify young transients)"

**Comment by svalenti** [comment]
"It is not clear why they say that such a search should avoid the ecliptic plane (I would guess the ecliptic latitude is irrelevant). The statements here are confusing."
I think we should rephrase the sentence:

"This criteria could be limited to the extragalactic sky,  away from both the ecliptic plane and the galactic plane, where recovery of Solar System objects puts less strain on the cadence requirements.

**Comment by svalenti** [comment]
The suggestion on deep drilling fields is not clear as there is no calculation of rates to support this statement.
We do not speak about rates, but we only mention that a cadence of 4-5 days (the DDF cadence today) is good only for transients that vary on a time scale larger than 4-5 days.

I suggest a small change in the text:
"Furthermore, we note that the currently envisioned deep drilling cadence prioritizes depth per visit at the expense of a higher cadence. One hour per night on a deep drilling field reaches a depth that not required for almost all transient science cases, and by cycling to a different field each night, the time between visits for a particular field (4-5 days) is too long for many important science cases. Even with higher overhead, a more useful approach for nearly all transient science, that the deep drilling fields are designed to facilitate, would be to observe the available fields each night for 15 or 20 minutes."

**Comment by fedhere** [comment]
incorporated stefano's response, I am closing this
