### ISSUE TITLE
Comments from David Kirkby (SAC) on 9.5 (Supernova Cosmology)

### ISSUE THREAD

**Issue by dkirkby** [LSSTScienceCollaborations/ObservingStrategy#634]
This looks good overall.

My only general comment on this section is that it is not always clear (to a non expert) which types of SNe are being referred to in different subsections: all types / Ia only / Ia + IIp / ...

Minor editorial comments / suggestions:
p.231: "a low and medium redshift *sample*..."
p.231: "...from supernova light *curves* in *conjunction* with..."
p.232: "...visible over *rest-frame* (?) time scales of..."
p.233: "...called 'science images'..." (reversed quote)
p.233: "...aside from noise" (remove "a")
p.235: 6 sig. digits on RA, DEC values in cadence plots seems overkill
p.236: "Technically, assuming..." (capitalization)
p.236: "...can compute the probability..." (omit "the value of")
p.239: "with a" repeated
p.239: "for this light *curve*, ..."
p.240: Why are the u-band observations clustered?  Add units to both axes.
p.241: The observed magnitudes here look consistent with a constant flux in all bands...

**Comment by drphilmarshall** [comment]
Thanks David! @jhrlsst would you like to take a shot at addressing David's comments please? Thanks!

**Comment by MichelleLochner** [comment]
@dkirkby Thanks so much for your comments! I'm submitting a pull request now which should deal with them. @rbiswas4 can you update the cadence plots with fewer decimal points on the RA and DEC?

"p.240: Why are the u-band observations clustered? Add units to both axes."
 -> To my knowledge this is a quirk of OpSim, u band is prioritised under certain conditions. Perhaps OpSim people can comment more but we don't discuss it because u band is usually seen as pretty unimportant for SNe. 
"p.241: The observed magnitudes here look consistent with a constant flux in all bands..."
-> Yes! This is almost our point. The cadence is so bad you almost can't even see there's a transient there.

**Comment by rbiswas4** [comment]
@dkirkby thanks for your comments:

- p.235: 6 sig. digits on RA, DEC values in cadence plots seems overkill : `fixed`
-  p240: Why are the u-band observations clustered? Add units to both axes : `fixed`. About the u band observations: The current way of dealing with the 5 filter slots and 6 filters is that grizy is in place most of the time. In contrast, around new moon, only u band is up in the DDF. This is easiest to see in the lowest panel of fig 9.16 around 49920 and ~49955. One of the big problems associated with this only `u` band approach is the gap it gets in the grizy sequences. This has been talked about with the OpSim people and hopefully this will go away in later versions of OpSim  
- p.241: The observed magnitudes here look consistent with a constant flux in all bands...  : 
Almost, but note in this figure 9.19, there are multiple observations as shown in fig 9.20. This means that the effective error bars are smaller.
