### ISSUE TITLE
Dust

### ISSUE THREAD

**Issue by pmmcgehee** [LSSTScienceCollaborations/ObservingStrategy#91]
@willclarkson, @akvivas...

In galaxy.tex the section dealing dust and the 3-D structure of the ISM needs to be expanded. Optical based techniques include the Bayesian approach from the PS1 team and the M dwarf based technique of McGehee+2015 [in prep].

**Comment by drphilmarshall** [comment]
Do we need to recruit a new section lead for this science project? Perhaps we should wait until @willclarkson has refactored the Galaxy chapter ( #99 ) though.

**Comment by willclarkson** [comment]
Thanks @pmmcgehee (cc @akvivas) - I absolutely agree. Would you like to take the lead on the Dust section? 

We are now using separate .tex files for sections within the MilkyWay chapter. In subdirectory MilkyWay/ you will find an example from the Solar Neighborhood (itself in huge need of more input) which follows the science-template.tex file @drphilmarshall created (a copy of that file is also in subdirectory MilkyWay/). I believe that has now been successfully merged with the "base" repository - pulling from "base master" should bring down the new version. 

I recommend you input your material into a copy of science-template.tex in subdirectory MilkyWay/ , since that is more likely to be compliant with the way the final product should look!

**Comment by pmmcgehee** [comment]
This is now part of the refactored Galaxy chapter and I am taking the lead on this topic. This issue is now closed.
